### PR TITLE
feat: disable CCache for jdk19+ as part of reproducible builds

### PR DESCRIPTION
**Pull request by zdtsw**
Ref: https://github.com/adoptium/temurin-build/issues/2973

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by zdtsw** [comment]
need help to merge it

**Comment by sxa** [comment]
@andrew-m-leonard @karianna @zdtsw Why was this not done for 17+? Presumably we'll want to do the same for the July releases which I believe we're aiming to build that way.

**Comment by karianna** [comment]
I was waiting for a separate PR on that

**Comment by andrew-m-leonard** [comment]
So jdk-18 upstream does not have all the necessary reproducible build patches.. and being STS, it goes out of support in September

**Comment by zdtsw** [comment]
https://github.com/adoptium/temurin-build/pull/3006 is on the "master" branch.
with both, it is disabled for jdk17 and jdk19+

**Pull request merged**
