### PR TITLE
enable headless for alpine builds

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Comment by gdams** [comment]
A simple test application to test if the binary is headless:

```java
import java.awt.*;

public class HeadlessBasics
{
    public static void main(String[] args)
    {
        // Check whether the application is
        // running in headless mode.
        GraphicsEnvironment ge = 
        GraphicsEnvironment.getLocalGraphicsEnvironment();
        System.out.println("Headless mode: " + ge.isHeadless());
    }
}
```

**Comment by gdams** [comment]
Seems to have worked:

```bash
/working-dir # ./jdk-16.0.2\+7/bin/java HeadlessBasics
Headless mode: true
```

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
PMC approved - failed tests are for unrelated reasons (we have another PR in the wings for that).

**Review by sxa — COMMENTED** [review]
Hmmm - can we not do this in our pipelines and leave the build scripts capable of building both as an option - this change will likely make it a bit more difficult for people to build a non-headless version from our scripts going forwards if they wish to do so.

**Comment by gdams** [comment]
> Hmmm - can we not do this in our pipelines and leave the build scripts capable of building both as an option - this change will likely make it a bit more difficult for people to build a non-headless version from our scripts going forwards if they wish to do so.

@sxa I'd prefer to make a change like that in our pipeline. This sits in our platform-specific configurations directory which is not the default path for other people using our scripts.

**Comment by sxa** [comment]
> @sxa I'd prefer to make a change like that in our pipeline. It creates a disconnect between the two repos and creates issues like the arm64 macOS bugs that I've just had to fix. This sits in our platform-specific configurations directory which is not the default path for other people using our scripts.

I presume your first sentence should have had a 'not' in it?

That disconnect was introduced when we split out piplines from the build repo (which I wasn't a fan of if I'm honest) and we have several other configure arguments for the different variants and platforms in places like https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/configurations/jdk11u_pipeline_config.groovy now. I'd be reluctant to add more things into what really ought to be configuration files specific to our ansible machine environment as opposed to configurable options affecting the JVM which it should be possible to override. It's not ideal having it two repositories but it's where we are and I don't want to put things in a different place just because of that, and certainly not just because a mistake was made with changing one such option.

(As an aside, when I build my own JDKs with our scripts I tend to use `make-adopt-build-farm.sh` in preference to `makejdk-any-platform.sh` because it's MUCH more usable for an end-user. I'd be quite surprised if many people actively chose to just use makejdk-any-platform on its own unless they didn't know about the other ones because the additional value it provides is quite low for other users IMHO so I don't think we should remove the ability to switch this on and off in those files without really good reason)

**Comment by karianna** [comment]
> A simple test application to test if the binary is headless:
> 
> ```java
> import java.awt.*;
> 
> public class HeadlessBasics
> {
>     public static void main(String[] args)
>     {
>         // Check whether the application is
>         // running in headless mode.
>         GraphicsEnvironment ge = 
>         GraphicsEnvironment.getLocalGraphicsEnvironment();
>         System.out.println("Headless mode: " + ge.isHeadless());
>     }
> }
> ```

Can we add that as an actual Smoke Test?

**Comment by karianna** [comment]
> > @sxa I'd prefer to make a change like that in our pipeline. It creates a disconnect between the two repos and creates issues like the arm64 macOS bugs that I've just had to fix. This sits in our platform-specific configurations directory which is not the default path for other people using our scripts.
> 
> I presume your first sentence should have had a 'not' in it?
> 
> That disconnect was introduced when we split out piplines from the build repo (which I wasn't a fan of if I'm honest) and we have several other configure arguments for the different variants and platforms in places like https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/configurations/jdk11u_pipeline_config.groovy now. I'd be reluctant to add more things into what really ought to be configuration files specific to our ansible machine environment as opposed to configurable options affecting the JVM which it should be possible to override. It's not ideal having it two repositories but it's where we are and I don't want to put things in a different place just because of that, and certainly not just because a mistake was made with changing one such option.
> 
> (As an aside, when I build my own JDKs with our scripts I tend to use `make-adopt-build-farm.sh` in preference to `makejdk-any-platform.sh` because it's MUCH more usable for an end-user. I'd be quite surprised if many people actively chose to just use makejdk-any-platform on its own unless they didn't know about the other ones because the additional value it provides is quite low for other users IMHO so I don't think we should remove the ability to switch this on and off in those files without really good reason)

So I think this boils down to:  Do we think headless is a sensible option for *all* users of our build scripts or only for our actual temurin builds?

I personally think it's OK to be headless for all users. I've yet to see any Alpine users using a Headful (is that the right term?) build...

Side note - I wonder if we should take temurin off the name of this repo and just have it as build scripts sometime in the future to make it clearer that anyone can use them.

**Comment by sxa** [comment]
> So I think this boils down to: Do we think headless is a sensible option for _all_ users of our build scripts or only for our actual temurin builds?

My view - absolutely only for temurin. There is no reason to actively disable this for anyone else, or even people using our scripts to build their own Temurin-equivalent binary. We have already had opinions expressed from at least two partiies that certain APIs not related to GUIs - image handling as I recall - may well not be available in such a build, so let's not make this something that we don't have an easy override mechanism for if others are using our build scripts and want a complete build, and we should ensure that we can switch back if required in the least intrusive way, which is in the Temurin build pipelines. This would be consistent with how we enable other JDK options such as dtrace enablement.

> Side note - I wonder if we should take temurin off the name of this repo and just have it as build scripts sometime in the future to make it clearer that anyone can use them.

Maybe - but they're maintained primarily for and by temurin, so I'm ok with it. But we absolutely must not forget when making changes that others may be using them (such as OpenJ9!) and take that into consideration when making changes - we have to have some responsibility to the user community and these scripts were intended to be used by others who want them. Dragonwell have already expressed an interest in having Alpine builds and we shouldn't force Temurin decisions such as this upon them.

**Comment by gdams** [comment]
related to https://github.com/adoptium/temurin-build/issues/2688

**Comment by gdams** [comment]
closing in favour of https://github.com/adoptium/ci-jenkins-pipelines/pull/190

**Pull request closed without merging**
