### PR TITLE
Enable debug images for all platforms including AIX

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM - I assume we did the AIX work to support this for all versions?

**Comment by andrew-m-leonard** [comment]
> LGTM - I assume we did the AIX work to support this for all versions?

@karianna yes, it's now merged into all versions jdk8,11,16,17

**Review by smlambert — APPROVED** [review]
thanks @andrew-m-leonard !

**Pull request merged**
