### PR TITLE
Simplify the parsing logic of makejdk_any_platform_args

### LINKED ISSUE #3955: Rebuild_Same_JDK_Reproducibility_Test_win fails with syntax error
**What are you trying to do?**
Trying to run the Rebuild_Same_JDK_Reproducibility_Test_win test target

**Expected behaviour:**
Expect it to run and pass

**Observed behaviour:**
It fails with the syntax error (shown below)
See also that it has failed continuously since August (see [Deep History in TRSS](https://trss.adoptium.net/deepHistory?testId=66d94124d24e1b006e76a279)), and also look at a recent run in Jenkins: https://ci.adoptium.net/job/Test_openjdk21_hs_dev.system_x86-64_windows_testList_1/7/

**Any other comments:**
```
[2024-09-05T00:23:41.557Z] Parameters Parsed Successfully
[2024-09-05T00:23:41.557Z] ---------------------------------------------
[2024-09-05T00:23:41.557Z] Building JDK...
[2024-09-05T00:23:41.557Z] sh: line 1: unexpected EOF while looking for matching `"'
[2024-09-05T00:23:41.557Z] sh: line 2: syntax error: unexpected end of file
[2024-09-05T00:23:41.557Z] -----------------------------------
[2024-09-05T00:23:41.557Z] Rebuild_Same_JDK_Reproducibility_Test_win_0_FAILED
```

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #3955

### CODE REVIEW

**Comment by sophia-guo** [comment]
Grinder :https://ci.adoptium.net/view/Test_grinder/job/Grinder/10987/console

```
13:04:21  make[5]: Entering directory '/cygdrive/c/comp-jdk-build/temurin-build/workspace/build/src'
13:04:21  Error: Cannot locate spec.gmk, given by SPEC=win_x86-64.
13:04:21  /cygdrive/c/comp-jdk-build/temurin-build/workspace/build/src/make/Init.gmk:124: *** Cannot continue.  Stop.
13:04:21  make[5]: Leaving directory '/cygdrive/c/comp-jdk-build/temurin-build/workspace/build/src'
13:04:21  OpenJDK make failed, archiving make failed logs
13:04:22  Archiving and compressing with gzip
13
```

@andrew-m-leonard the build and error message I got

**Comment by sophia-guo** [comment]
grinder https://ci.adoptium.net/view/Test_grinder/job/Grinder/11002/ - unset SPEC temporarily. 

@andrew-m-leonard see the grinder unset SPEC temporarily is the test results good?

**Comment by andrew-m-leonard** [comment]
> grinder https://ci.adoptium.net/view/Test_grinder/job/Grinder/11002/ - unset SPEC temporarily.
> 
> @andrew-m-leonard see the grinder unset SPEC temporarily is the test results good?

@sophia-guo good to see unsetting SPEC resolved the autoconf failure

The 3 differing files are caused by a failure in patching the SystemModule classes:
```
17:05:57  find: '': No such file or directory
17:05:57  find: '': No such file or directory
17:05:57  find: '': No such file or directory
17:05:57  Successfully removed all SystemModules jdk.jpackage hash differences from 
```
It was clearly not "Successful" !!
I think it is this find line that is failing: https://github.com/adoptium/temurin-build/blob/79bb2763471fbe65ecb101d94e470514024bf7f9/tooling/reproducible/repro_common.sh#L96

I am not sure why ${JDK_DIR} is not being resolved, but I wonder if these two functions should be changed to have it passed as a param, like all the others are:
```
function removeSystemModulesHashBuilderParams() {
function processModuleInfo() {
```

**Comment by sophia-guo** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/11051/

**Review by karianna — APPROVED** [review]

**Review by andrew-m-leonard — APPROVED** [review]
looks ok

**Pull request merged**
