### PR TITLE
update: move function from build-farm to build.sh (reproducible build)

### PR DESCRIPTION
**Pull request by zdtsw**
Ref: https://github.com/adoptium/temurin-build/issues/2973
Ref: https://github.com/adoptium/temurin-build/pull/3026#issuecomment-1176103066

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by zdtsw** [comment]
> Agree with this in theory, but given the checks have failed we should definitely run it through a local test build and verify that it works before this is ready for merge.

yeah, i did a fix on syntax, will run with RELEASE=true tomorrow on jenkins first

**Review by gdams — APPROVED** [review]

**Comment by zdtsw** [comment]
test jdk(20) + release==true + linux
expect: --with-source-data=version --disable--cache
log: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-temurin/201/console
`08:49:00  using configure arguments '--verbose --with-vendor-name='Eclipse Adoptium' --with-vendor-url=https://adoptium.net/ --with-vendor-bug-url=https://github.com/adoptium/adoptium-support/issues --with-vendor-vm-bug-url=https://github.com/adoptium/adoptium-support/issues --without-version-opt --without-version-pre --with-version-build=4 --with-vendor-version-string=Temurin-20+4 --with-boot-jdk=/home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-x64-temurin/jdk-19 --with-debug-level=release --with-native-debug-symbols=external --with-source-date=version --disable-ccache --with-build-user=adoptium --with-jvm-variants=server --with-cacerts-src=/home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-x64-temurin/sbin/../security/certs --disable-warnings-as-errors --enable-dtrace'.`

test jdk(20) + release==false + linux
expect: --enable-ccache
log: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-aarch64-temurin/84/console
`Completed configuring the version string parameter, config args are now:  --with-vendor-name="Eclipse Adoptium" --with-vendor-url=https://adoptium.net/ --with-vendor-bug-url=https://github.com/adoptium/adoptium-support/issues --with-vendor-vm-bug-url=https://github.com/adoptium/adoptium-support/issues --with-version-opt=202207070653 --with-version-pre=beta --with-version-build=4 --with-vendor-version-string=Temurin-20+4-202207070653 --with-boot-jdk=/home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-aarch64-temurin/jdk-19 --with-debug-level=release --with-native-debug-symbols=external --with-jvm-variants=server --with-cacerts-src=/home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-aarch64-temurin/sbin/../security/certs  --disable-warnings-as-errors --enable-ccache --with-source-date=updated --with-build-user=adoptium --enable-dtrace
`

test jdk18 + release==true + linux
expect: --enable-ccache
log: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-linux-x64-temurin/71/console
` Completed configuring the version string parameter, config args are now:  --with-vendor-name="Eclipse Adoptium" --with-vendor-url=https://adoptium.net/ --with-vendor-bug-url=https://github.com/adoptium/adoptium-support/issues --with-vendor-vm-bug-url=https://github.com/adoptium/adoptium-support/issues --without-version-opt --without-version-pre --with-version-build=2 --with-vendor-version-string=Temurin-18.0.1.1+2 --with-boot-jdk=/usr/lib/jvm/jdk-17 --with-debug-level=release --with-native-debug-symbols=external --enable-ccache --with-jvm-variants=server --with-cacerts-file=/home/jenkins/workspace/build-scripts/jobs/jdk18u/jdk18u-linux-x64-temurin/sbin/../security/cacerts  --disable-warnings-as-errors --enable-dtrace
`
test jdk11 + release==true + mac
expect: --enable-ccache
log: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-temurin/84/console
`
Completed configuring the version string parameter, config args are now:  --with-vendor-name="Eclipse Adoptium" --with-vendor-url=https://adoptium.net/ --with-vendor-bug-url=https://github.com/adoptium/adoptium-support/issues --with-vendor-vm-bug-url=https://github.com/adoptium/adoptium-support/issues --without-version-opt --without-version-pre --with-version-build=7 --with-vendor-version-string=Temurin-11.0.16+7 --with-boot-jdk=/Library/Java/JavaVirtualMachines/adoptopenjdk-10.jdk/Contents/Home --with-jvm-features=shenandoahgc --with-debug-level=release --with-native-debug-symbols=external --enable-ccache --with-jvm-variants=server --with-cacerts-file=/Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-temurin/sbin/../security/cacerts  --disable-warnings-as-errors --with-extra-cxxflags=-mmacosx-version-min=10.9 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/ --enable-dtrace=auto --with-freetype=bundled
`

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
