### PR TITLE
Don't bundle zlib for OpenJ9 builds

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Related #3459 eclipse-openj9/openj9#18127

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@tellison @sxa for review please.

**Review by sxa — APPROVED** [review]
Interesting on the hardware acceleration ...

**Review by karianna — APPROVED** [review]

**Comment by AdamBrousseau** [comment]
Is the Code Freeze for the 21 release lifted?

**Comment by sxa** [comment]
> Is the Code Freeze for the 21 release lifted?

That's a bit of a loaded question, but I'll let this in :-)

**Pull request merged**
