### PR TITLE
feat: Cleanup GH Action on windows-2016 (deprecated)

### PR DESCRIPTION
**Pull request by zdtsw**

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by zdtsw** [comment]
@andrew-m-leonard can I get another review on this?

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
@zdtsw we ought to tidy up the Lint errors?

**Comment by zdtsw** [comment]
> @zdtsw we ought to tidy up the Lint errors?

yeah, i have another [PR](https://github.com/adoptium/temurin-build/pull/2924) fixing these linter erros, not sure what happened but they just got all checks since last night~~~ :crab:

**Pull request merged**
