### PR TITLE
feat: enable --create-sbom to set in ci-jenkins-pipeline instead default

### PR DESCRIPTION
**Pull request by zdtsw**
Ref: https://github.com/adoptium/temurin-build/issues/2900

### CODE REVIEW

**Comment by sophia-guo** [comment]
This should be created as the reverse of https://github.com/adoptium/temurin-build/pull/2926/files?

**Comment by zdtsw** [comment]
> This should be created as the revert of https://github.com/adoptium/temurin-build/pull/2926/files?

Yes, it is to revert back to the old logic -- default to "false"

**Comment by sophia-guo** [comment]
Screen Shot 2022-05-16 at 1 23 00 PM

Using the revert button is probably an easier and correct way.

**Comment by zdtsw** [comment]
> Screen Shot 2022-05-16 at 1 23 00 PM
> 
> Using the revert button is probably an easier and correct way.

made a new [PR](https://github.com/adoptium/temurin-build/pull/2930), revert old one and have this one closed

**Pull request closed without merging**
