### PR TITLE
dependency_data files do not need licenses

### PR DESCRIPTION
**Pull request by adamfarley**
...on the basis that they only contain version strings, jar names, and SHAs that are obtained from external sources.

### CODE REVIEW

**Review by tellison — APPROVED** [review]

**Comment by tellison** [comment]
Do you need to remove some incorrectly added too?

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
@adamfarley Feel free to merge once you've addressed Tim's Q.

**Comment by adamfarley** [comment]
> Do you need to remove some incorrectly added too?

I don't think so, no. I'm adding just one entry, and it exclusively covers a directory that contains sha256 files and version string files.

I did review the rest of the list. Maybe you're suggesting that getDependencies should have a license at the top of that groovy file, and its entry be excluded here? I didn't think it did, as other groovy files in our repos don't have licenses ([example](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/aqaTestPipeline.groovy)).

**Comment by adamfarley** [comment]
Thanks @gdams

**Pull request merged**
