### PR TITLE
GH: add changes in security folder for testing

### PR DESCRIPTION
**Pull request by zdtsw**
- if cacerts is changed we need to test it too

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@zdtsw I think if you rebase that linter problem will go away

**Comment by zdtsw** [comment]
testing and see if 5f29310c05927086842c083d113a65efedd11e45 is the reason why windows-2019 GH action checks are failing.

**Comment by zdtsw** [comment]
> testing and see if [5f29310](https://github.com/adoptium/temurin-build/commit/5f29310c05927086842c083d113a65efedd11e45) is the reason why windows-2019 GH action checks are failing.

seems not related to action/cache, 
and from history log, it never found the keypath from cache for windows check.

**Comment by zdtsw** [comment]
close this one, it is done in https://github.com/adoptium/temurin-build/pull/3213 with fix of smoketest

**Pull request closed without merging**
