### PR TITLE
Update all references of support url github.com/AdoptOpenJDK/openjdk-support to github.com/adoptium/adoptium-support

### PR DESCRIPTION
**Pull request by ljessicc**

### CODE REVIEW

**Comment by karianna** [comment]
@ljessicc You'll need to rebase and sign the Eclipse CLA (http://www.eclipse.org/legal/CLA.php)

**Comment by ljessicc** [comment]
@karianna OK. thank you

**Comment by ljessicc** [comment]
I did a rebase, however when I try to commit and push it says everything is up to date and I signed the Eclipse LCA

**Comment by karianna** [comment]
@ljessicc can you rebase again, looks like merge conflicts.  Can you also update the title of this PR to describe what it is :-)

**Comment by ljessicc** [comment]
> @ljessicc can you rebase again, looks like merge conflicts. Can you also update the title of this PR to describe what it is :-)

ok

**Comment by karianna** [comment]
@ljessicc looks like rebase is required again

**Comment by karianna** [comment]
This has been superseded - thanks for your submission!

**Pull request closed without merging**
