### PR TITLE
Force TZ=UTC for reproducible release builds

### PR DESCRIPTION
**Pull request by sxa**
Fixes https://github.com/adoptium/temurin-build/issues/3075

While most timestamps in the builds are neutralised when some of the files are produced there are some files which have timestamps that are affected by the time zone setting, so if you build on a machine in a different time zone then the builds are not identical. I've seen this on xLinux (Timestamps within the `ct.sym` zipfile are different) as well as in the issue reference above between two Linux/s390x systems. This fix will set `TZ=UTC` alongside the other options when the reproducible builds are enabled.

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by sxa** [comment]
(Draft as the fix in here may not be working, although it does when I set the variable standalone in the calling shell)

**Comment by sxa** [comment]
Smoke test failure raised at https://github.com/adoptium/temurin-build/issues/3093 but seems unlikely it's related to this PR

**Comment by sxa** [comment]
> Smoke test failure raised at #3093 but seems unlikely it's related to this PR

Have done a revert on the change and the checks all appear to be passing ... Hmmm. Will re-push and try again with `TZ=UTC`

**Comment by sxa** [comment]
It's looking ok this time - some of the non-Alpine linuxes are now passing. No idea what happened there. I added a change to revert what I did and have now removed the revert and it seems ok, so adding some explicit reviewers to this PR now.

**Comment by sxa** [comment]
NOTE: I will not be around for the next week so if there are any problems when this is merged, others should feel empowered to revert/fix as appropriate.

**Comment by sxa** [comment]
(Final push to do a whitespace adjustment)

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
