### PR TITLE
Update OpenJ9 builds to use OpenSSL 1.1.1o

### PR DESCRIPTION
**Pull request by keithc-ca**
See also eclipse-openj9/openj9#14994.

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@karianna can we get some reviews on this please?

**Review by karianna — APPROVED** [review]
LGTM

**Comment by keithc-ca** [comment]
OpenJ9 should be using configure option `--with-openssl=fetched` and so any version that might be installed via ansible is irrelevant. I think we need to get #2550 or equivalent merged.

**Comment by AdamBrousseau** [comment]
We have "windows fetched" on Semeru side, I can put the PR together to upstream it to Adopt.

**Comment by sxa** [comment]
> We have "windows fetched" on Semeru side, I can put the PR together to upstream it to Adopt.

SGTM :-)

**Comment by AdamBrousseau** [comment]
https://github.com/adoptium/temurin-build/pull/2917

**Comment by AdamBrousseau** [comment]
I think this is ready to go in now that 2917 is merged.

**Review by sxa — APPROVED** [review]
This should be good now. I've also raised https://github.com/adoptium/infrastructure/issues/2554 so we can clear up the older versions which were installed on the windows systems

**Comment by sxa** [comment]
Running a new pipeline at https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1939/ to verify

**Comment by sxa** [comment]
LGTM - build completed ok at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/1156/consoleFull (restricted access)

**Pull request merged**
