### PR TITLE
Change default TARGET_FILE_NAME to include -jdk

### LINKED ISSUE #2700: Default TARGET_FILE_NAME doesn't include '-jdk', causing filename clash
When using `./makejdk-any-platform.sh` locally it builds a test image, a jdk image and a jre image **by default**. However, the tarball names of test image and jre image depend on `TARGET_FILE_NAME` to contain string `-jdk`. Otherwise the name remains unchanged. Incidentally the default value of `TARGET_FILE_NAME` is `OpenJDK.tar.gz` which is bad as whichever one gets produced last will win (possibly not containing a JDK in `OpenJDK.tar.gz`.

```
$ grep -rn TARGET_FILE_NAME
sbin/common/config_init.sh:92:TARGET_FILE_NAME
sbin/common/config_init.sh:315:        BUILD_CONFIG[TARGET_FILE_NAME]="$1"; shift;;
sbin/common/config_init.sh:456:  BUILD_CONFIG[TARGET_FILE_NAME]="OpenJDK.tar.gz"
sbin/build.sh:563:    local makeFailureLogsName=$(echo "${BUILD_CONFIG[TARGET_FILE_NAME]//-jdk/-makefailurelogs}")
sbin/build.sh:1131:    local jreName=$(echo "${BUILD_CONFIG[TARGET_FILE_NAME]}" | sed 's/-jdk/-jre/')
sbin/build.sh:1136:    local testImageName=$(echo "${BUILD_CONFIG[TARGET_FILE_NAME]//-jdk/-testimage}")
sbin/build.sh:1141:    local debugImageName=$(echo "${BUILD_CONFIG[TARGET_FILE_NAME]//-jdk/-debugimage}")
sbin/build.sh:1144:  createArchive "${jdkTargetPath}" "${BUILD_CONFIG[TARGET_FILE_NAME]}"
```

### PR DESCRIPTION
**Pull request by jerboaa**
Closes #2700

### CODE REVIEW

**Comment by karianna** [comment]
@jerboaa I don't think the GH Action failures are down to your tests, but do you know how to get past the SEALED classes compiler bug for tip?

**Comment by jerboaa** [comment]
> @jerboaa I don't think the GH Action failures are down to your tests, but do you know how to get past the SEALED classes compiler bug for tip?

@karianna see https://github.com/adoptium/temurin-build/pull/2702#issuecomment-915043130

Yes, failures seem unrelated.

**Review by karianna — APPROVED** [review]
LGTM - will have to see if it has any downstream impact in pieplines.

**Review by sxa — APPROVED** [review]
Based on the comments in https://github.com/adoptium/temurin-build/issues/2700#issue-990273751 and the associated code in `createOpenJDKTarArchive` at https://github.com/adoptium/temurin-build/blob/559f9a545133b5f717a16e237c3f3e2746094b4a/sbin/build.sh#L1121 this makes sense so I approve

**Pull request merged**
