### PR TITLE
Fix Windows codesign permissions

### PR DESCRIPTION
**Pull request by gdams**
Currently, the executable bit isn't added back to the codesigned binary:

```bash
bin/java: Permission denied
```

### CODE REVIEW

**Comment by karianna** [comment]
@gdams 

Found 1 clones.
ERROR: jscpd found too many duplicates (2.49%) over threshold (0%)
Error: ERROR: jscpd found too many duplicates (2.49%) over threshold (0%)
    at ThresholdReporter.report (/node_modules/@jscpd/finder/dist/reporters/threshold.js:12:19)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:82:26
    at Array.forEach (<anonymous>)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:81:28
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by gdams** [comment]
@karianna I'll refactor in a follow up PR if that's okay

**Review by karianna — APPROVED** [review]
lgtm

**Review by sxa — COMMENTED** [review]
Does the cygwin `chmod` have the `--reference` option? If so this would be simpler:
```
chmod --reference="@${dir}/unsigned_${file}" "$f"
```

**Comment by gdams** [comment]
@sxa thanks for the tip. Updated PTAL

**Review by sxa — APPROVED** [review]
LGTM

**Pull request merged**
