### PR TITLE
Fix failing jdk11 macos CI checks due to Xcode 15 dependencies

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
- Xcode 15 prereqs at least OSX >13.5, hence jdk11+ are now built on OSX 14
- We are also building using Xcode 15.2 now, that has bug fixes

### CODE REVIEW

**Comment by karianna** [comment]
@andrew-m-leonard not sure if 11u failure is due to this compiler toolchain version change.

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard not sure if 11u failure is due to this compiler toolchain version change.

yeah, I am trying to work that one out...

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]

**Pull request merged**
