### PR TITLE
Fix commit URL in RELEASING.md which looks like it got changed in an invalid way

### PR DESCRIPTION
**Pull request by sxa**
Fix is obvious - it is currently incorrect and therefore useless.

### CODE REVIEW

**Comment by karianna** [comment]
Looks like https://github.com/adoptium/temurin-build/runs/5155472965?check_suite_focus=true has text linter issues, not sure how easy that is to fix/escape?

**Comment by sxa** [comment]
> Looks like https://github.com/adoptium/temurin-build/runs/5155472965?check_suite_focus=true has text linter issues, not sure how easy that is to fix/escape?

I'd rather that was done under a standalone PR, but we should try and ensure that when the linter is upgraded that it is verified to pass so that people don't suddenly get unrelated failures. I raised an issue about this last month. https://github.com/adoptium/temurin-build/issues/2831

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
Closing as it looks like this got included in https://github.com/adoptium/temurin-build/pull/2905/files

**Pull request closed without merging**
