### PR TITLE
Fix TemurinSignSBOM build failures due to upstream pki jar changes

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
openkeystore updates to change their jar name
and fix TemurinSignSBOM.java incorrect exception handling

Fixes https://github.com/adoptium/temurin-build/issues/3364

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]

**Comment by zdtsw** [comment]
maybe we can consider to use their release tag e.g https://github.com/cyberphone/openkeystore/releases/tag/1.0.0  instead only clone repo on default branch?

**Review by sxa — APPROVED** [review]
Approving, noting that this is SBOM upstream tooling that has given the need for the change, not OpenJDK.

**Comment by andrew-m-leonard** [comment]
> maybe later, we can consider to use their release tag e.g https://github.com/cyberphone/openkeystore/releases/tag/1.0.0 instead only clone repo on default branch?

ah good spot, that's new, they weren't providing release previously

**Comment by andrew-m-leonard** [comment]
@zdtsw So they have tagged a release 1.0.0 level, I have updated this PR to clone that specific tag which is far safer.

**Pull request merged**
