### PR TITLE
Ensure Mac Plist update to Temurin is performed for only jdk8

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes https://github.com/adoptium/temurin-build/issues/2949

Ensures Mac Plist change to Eclipse Temurin is only done for jdk8, and logic is correctly checked for jdk11+.

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM - Are we not changing 8 because it would break backwards compat?

**Comment by andrew-m-leonard** [comment]
@karianna I believe that's still up for discussion in the Steering group, @smlambert ?
This PR just fixes the build inconsistency with jdk11+

**Comment by andrew-m-leonard** [comment]
Test builds:

Mac jdk17u:
```
                <key>JVMVendor</key>
                <string>Eclipse Adoptium</string>
```

Mac jdk8u:
```
                <key>JVMVendor</key>
                <string>Eclipse Temurin</string>
```

**Review by sxa — COMMENTED** [review]
Without understanding the intricacies of the options that lead to the discovery of this I'm a little unclear on one thing: Does this change the defaults that will come out during the nightly and/or release pipelines, or will it only affect builds using non-default options in the pipelines?

**Comment by andrew-m-leonard** [comment]
> Without understanding the intricacies of the options that lead to the discovery of this I'm a little unclear on one thing: Does this change the defaults that will come out during the nightly and/or release pipelines, or will it only affect builds using non-default options in the pipelines?

I found this issue when building on my Mac with a plain build-farm/make-adopt-build-farm.sh (no exploded/assemble two phase build), the end result being different to Jenkins in the Plist file. The reason being my build ran the configureCommandParameters and changed the Plist value.

@sxa The end result for nightlies and releases will be the same, due to the addition of the jdk8 check now that configureCommandParameters() is being called from the assemble-exploded phase.

**Pull request merged**
