### PR TITLE
Rename openjdkbinary folder to jdkbinary

### PR DESCRIPTION
**Pull request by llxia**
depends on https://github.com/adoptium/aqa-tests/pull/4837

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by llxia** [comment]
@smlambert could you review this PR? Thanks

**Review by smlambert — APPROVED** [review]
Thanks @llxia !

**Comment by smlambert** [comment]
I presume the code freeze will be lifted this week (@sophia-guo ?) otherwise we can also thaw this to merge.

/thaw

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
