### PR TITLE
bump JDK17 to JDK17u

### PR DESCRIPTION
**Pull request by gdams**
JDK17u repo has now been mirrored

### CODE REVIEW

**Comment by gdams** [comment]
Linter rule can be ignored

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
After PMC discussion we decided to keep this at 17 as upstream may not add the GA tag upstream into 17u until well after the GA release.

**Review by johnoliver — APPROVED** [review]

**Comment by karianna** [comment]
Smoke tests failing for unrelated reasons.

**Pull request merged**
