### PR TITLE
Add support for Windows Redist DLL as Adoptium DevKit

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes https://github.com/adoptium/temurin-build/issues/3887

Adds partial support for an Adoptium Windows DevKit, that consists of purely the Redist DLLs from https://github.com/adoptium/devkit-binaries/releases/tag/vs2022_redist_14.40.33807_10.0.26100.0

eg.
```
--use-adoptium-devkit vs2022_redist_14.40.33807_10.0.26100.0
```

**Test builds:**
- jdk17u Windows x64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x64-temurin/536/ - Success
- jdk17u Windows x86-32 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x86-32-temurin/367/ - Success
- jdk21u Windows x64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-windows-x64-temurin/169/
- jdk21u Windows aarch64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-windows-aarch64-temurin/7/ - Success

AQA Triage tests: https://github.com/adoptium/ci-jenkins-pipelines/issues/1104#issuecomment-2393086371

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Review by sxa — COMMENTED** [review]
I'd really prefer (even if we have this as a fallback) for it to be done in the playbooks so it is consistently on the machines instead of being dynamically downloaded. I don't really want to introduce more non-hermetic parts of the build process if possible.

**Comment by andrew-m-leonard** [comment]
> I'd really prefer (even if we have this as a fallback) for it to be done in the playbooks so it is consistently on the machines instead of being dynamically downloaded. I don't really want to introduce more non-hermetic parts of the build process if possible.

@sxa 
It's the same as Linux devkit, so the ansible playbooks can install locally into:
```
/usr/local/devkit/vs2022_redist_14.40.33807_10.0.26100.0
```
and will only pull if not on the build machine

**Comment by andrew-m-leonard** [comment]
@sxa Where would you suggest for the local files on Windows ?

**Comment by sxa** [comment]
> @sxa It's the same as Linux devkit, so the ansible playbooks can install locally into:
> `/usr/local/devkit/vs2022_redist_14.40.33807_10.0.26100.0`
> and will only pull if not on the build machine

Yeah `/usr/local` would probably end up under `c:\cygwin64` which isn't ideal.

To be honest unless we want to create some new directory under `C:\program Files` or `C:\devkit` I'd kinda be happy putting it under `C:\openjdk` (where we've prototyped it) so I guess one of those three options. 

FYI @steelhead31 since he was involved in some of these discussions.

**Comment by andrew-m-leonard** [comment]
> > @sxa It's the same as Linux devkit, so the ansible playbooks can install locally into:
> > `/usr/local/devkit/vs2022_redist_14.40.33807_10.0.26100.0`
> > and will only pull if not on the build machine
> 
> Yeah `/usr/local` would probably end up under `c:\cygwin64` which isn't ideal.
> 
> To be honest unless we want to create some new directory under `C:\program Files` or `C:\devkit` I'd kinda be happy putting it under `C:\openjdk` (where we've prototyped it) so I guess one of those three options.
> 
> FYI @steelhead31 since he was involved in some of these discussions.

Yes, I think given it's Windows, defaulting to say c:\openjdk as a local search location is probably fine. i'll update PR with that change, thanks

**Comment by andrew-m-leonard** [comment]
Infra issue to extract onto Adoptium build nodes: https://github.com/adoptium/infrastructure/issues/3772

**Review by sxa — APPROVED** [review]
Approved now that the infrastructure issue is in flight and this will be a backup option for that :-)

**Pull request merged**
