### PR TITLE
Removing also dash "-" and underscore "_" from repository name

### PR DESCRIPTION
**Pull request by judovana**
this is partially bound to https://github.com/adoptium/temurin-build/pull/3724, where dash and underscore are one of major delimiters in directory names jdk11u-my_feature

May, or may have not sense without the 3724

### CODE REVIEW

**Comment by judovana** [comment]
Please let me know, if this have sense standalone, or only as part of  https://github.com/adoptium/temurin-build/pull/3724

**Comment by karianna** [comment]
Let's make it part of 3724, easier to track the discussion there.

**Comment by judovana** [comment]
Sure! ty!

**Comment by judovana** [comment]
Just for record. This PR was very wrong. The final argumenr, which is santised on this line, is strictly `jdk[XY[u]]`  nothing else. In theory,  the  sed shold not be enhanced, but make more strict.  and remove jsut ` [jdku]` letters

I will do a PR, which will be asserting that the mandatory  argument of jdkXY is correct.

**Comment by judovana** [comment]
Surpassed by https://github.com/adoptium/temurin-build/pull/3728

**Pull request closed without merging**
