### PR TITLE
Fix OS architecture for darwin aarch64 builds of static libs

### PR DESCRIPTION
**Pull request by zakkak**
This is a follow up to https://github.com/adoptium/temurin-build/pull/2725.

`uname -m` seems to return `arm64` on MacOS but the expected naming
seems to be `aarch64` ( which is consistend with linux and windows as
well) as observed in https://github.com/graalvm/mandrel-packaging/pull/415#issuecomment-2134025210

cc @jerboaa

### CODE REVIEW

**Review by karianna — APPROVED** [review]
Seems OK, would be good to get a full refactor of build vs target architectures.

**Comment by zakkak** [comment]
@karianna thanks for the review. Is there anything special I need to do for the ECA check? I switched the email used in my commit to use the one associated with my eclipse account but it doesn't seem to pick up the change.

**Comment by jerboaa** [comment]
@zakkak Have you looked at the troubleshooting tips here https://api.eclipse.org/git/eca/status/gh/adoptium/temurin-build/3827?

**Comment by zakkak** [comment]
> @zakkak Have you looked at the troubleshooting tips here https://api.eclipse.org/git/eca/status/gh/adoptium/temurin-build/3827?

Yes, and that's why I tried changing the email address of my commit (to match the one I use for my eclipse account) but the check still references my redhat email.

> Have you tested this works for a mandrel build on mac aarch?

Unfortunately not. I might be able to perform such a test next week.

**Comment by jerboaa** [comment]
> Yes, and that's why I tried changing the email address of my commit (to match the one I use for my eclipse account) but the check still references my redhat email.

Have you signed the ECA recently? You may have to re-sign if it's from an old account.

**Comment by zakkak** [comment]
> > Yes, and that's why I tried changing the email address of my commit (to match the one I use for my eclipse account) but the check still references my redhat email.
> 
> Have you signed the ECA recently? You may have to re-sign if it's from an old account.

Signed it yesterday using my `foivos at zakkak dot net` eclipse account. The issue appears to be that when I opened the PR I used my redhat email in the commit message and the ECA check seems to keep trying to verify against my redhat email despite me force pushing a new commit with the author set to `foivos at zakkak dot net`.

**Comment by jerboaa** [comment]
Sorry no idea, then :(

**Comment by karianna** [comment]
I tried to force the validation again but fail, you may need to redo the PR sorry :-(

**Comment by zakkak** [comment]
After trying a few things what worked out turned out to be the following:

1. Create a new branch based on the branch used in this PR
2. Create a new PR using that PR
3. The ECA re-runs, this time using the right e-mail address
4. Close the new PR, as the re-run is reflected on the old PR

**Pull request merged**
