### PR TITLE
Add lib jcommander for smoke test

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Add lib jcommander for smoke test
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/19122

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Links:
- hotspot: https://ci.adoptium.net/job/Grinder/9276/console
```
15:22:35       [exec] dependencyList is set to testng,jcommander
15:22:35       [exec] --------------------------------------------
15:22:35       [exec] Starting download third party dependent jars
15:22:35       [exec] --------------------------------------------
15:22:35       [exec] downloading dependent third party jars to /home/jenkins/workspace/Grinder/../../testDependency/lib
15:22:35       [exec] /home/jenkins/workspace/Grinder/../../testDependency/lib/jcommander.jar exists with correct hash, not downloading
15:22:35       [exec] /home/jenkins/workspace/Grinder/../../testDependency/lib/testng.jar exists with correct hash, not downloading
15:22:35       [exec] downloaded dependent third party jars successfully
```
- openj9: hyc_grinder 39114

**Review by karianna — APPROVED** [review]

**Review by llxia — APPROVED** [review]

**Review by smlambert — APPROVED** [review]

**Pull request merged**
