### PR TITLE
Add --create-sbom to README.md

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]

**Comment by karianna** [comment]
@andrew-m-leonard needs rebase

**Review by sxa — CHANGES_REQUESTED** [review]
> Can this be added into https://github.com/adoptium/temurin-build/blob/master/makejdk-any-platform.1 too 

Ading a block on this as we don't want to have out of date information. Also in light of other conversations it looks like creating the SBOM is happening by default even without this option being specified which is probably not desired behavior

**Comment by andrew-m-leonard** [comment]
@sxa added to [makejdk-any-platform.1](https://github.com/adoptium/temurin-build/blob/master/makejdk-any-platform.1)
and default being reverted to false: https://github.com/adoptium/temurin-build/pull/3053

**Comment by andrew-m-leonard** [comment]
Alpine failures unrelated

**Comment by andrew-m-leonard** [comment]
@sxa I think this is good now

**Review by sxa — APPROVED** [review]
LGTM

**Pull request merged**
