### PR TITLE
Cleanup excessive linter checks

### PR DESCRIPTION
**Pull request by M-Davies**
Commiters have identified that the super linter checks are excessively strict, so this pr attempts to summarise and eliminate checks that appear non-blocking to the Adoptium community

Fixes: #2581 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM - we can look at enabling more linting as time goes by.

**Review by andrew-m-leonard — APPROVED** [review]
good

**Comment by M-Davies** [comment]
@karianna Can you merge?

**Review by smlambert — APPROVED** [review]
thanks @M-Davies !

**Pull request merged**
