### PR TITLE
Improve Alpine Version In SBOM

### LINKED ISSUE #2997: OS_FULL_VERSION doesn't list Alpine OS version
Noted while reverting from Alpine 3.16 to Alpine 3.15 in https://github.com/adoptium/infrastructure/pull/2628

The recent change to use `OS_FULL_VERSION` in the SBOM (https://github.com/adoptium/temurin-build/pull/2991) means that the OS is [showing as](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-alpine-linux-x64-temurin/69/consoleFull)
```
16:56:21  BUILD_CONFIG[OS_FULL_VERSION]="Linux 4.15.0-1113-azure : Alpine Linux"
```
which doesn't explicitly list the Alpine version (Only the kernel, which is dependent on the host it's running on)

We should probably modify https://github.com/adoptium/temurin-build/blob/abb4d36cfe18ceb3be70d8b30d28a1eae4262863/sbin/common/config_init.sh#L387 to pull the PRETTY_NAME from `/etc/os-release` or maybe just the whole contents of `alpine-release` which just has the version number bolted on to the end of the current output

### PR DESCRIPTION
**Pull request by steelhead31**
Fixes #2997

SBOM now lists the alpine os version number, e.g Alpine Linux 3.14, rather than the underlying O/S Kernel version.

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Review by zdtsw — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Weird, anyone know why Wen's approval isn't registering?

**Comment by steelhead31** [comment]
@zdtsw are you still having issues with your commiter status ?

**Comment by zdtsw** [comment]
maybe..... i still cannot merge my only commit after 2 approvals or count my approval to others.

**Comment by karianna** [comment]
Hmm, that doesn't seem right, I'd email the Eclipse Foundation on this one.

**Comment by zdtsw** [comment]
> Hmm, that doesn't seem right, I'd email the Eclipse Foundation on this one.

thanks!

**Pull request merged**
