### PR TITLE
Fix Adopt_J9_FeatureTests_0

### PR DESCRIPTION
**Pull request by LongyuZhang**
- fix Adopt_J9_FeatureTests_0
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/14952 ibm_git/runtimes/backlog/issues/796

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test LInks:

Hotspot:
- aix 8: https://ci.adoptopenjdk.net/job/Grinder/4923/
- aix 11: https://ci.adoptopenjdk.net/job/Grinder/4924/
- aix 17: https://ci.adoptopenjdk.net/job/Grinder/4925/

Openj9 (hyc_grinder):
- jdk 8:  mac:      24455      win:  24458       aix: 24461
- jdk 11: mac:     24456        win:24459        aix: 24462
- jdk 17: mac:      24457       win: 24460       aix: 24470

**Comment by LongyuZhang** [comment]
@pshipton @llxia @smlambert Could you review it? Thanks.

**Comment by pshipton** [comment]
lgtm

**Review by llxia — APPROVED** [review]
LGTM. Thanks @LongyuZhang

**Review by smlambert — APPROVED** [review]
thanks @LongyuZhang !

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
