### PR TITLE
Creating regex logic for build autotriager

### LINKED ISSUE #3521: Weekly build triage - Automation
**Summary**

To automate the process of build failure triage.

Note, this does include propagated red test framework failures, but will not include unit test failure.

**MVP**

Steps 1-3, as per the full plan below.

**Full Plan**

- [x] Step 1) A GitHub Action calls a script on Mondays.
- [x] Step 2) The script identifies the latest automated build pipelines, limited to the last 7 days, for each current JDK major version.
- [x] Step 3) The script then identifies which subjobs failed.
- [x] Step 4) We then access each failed subjob and use a list of easily-modified patterns to identify useful output relevant to the failure.
  - 3-4ph: Draw up list of initial regexs and any (rough) relevant data.
  - 1-4ph: Test regexs and fix bugs.
  - 1pd: Approximate Total.
  - Actual time: 1.6pd
    - Note: Creating the logic to actually apply the regexs took longer than expected. Make sure to set aside time for supporting logic in future estimations.
- [x] Step 5) Each pattern should be associated with metadata, including problem type, advice, any relevant issue links, and whether it is generally considered a preventable issue.
  - 2-3ph: Tidy metadata and identify preventables.
  - 1-2ph: Test metadata displays correctly.
  - 0.5pd: Approximate Total.
  - Actual time: 0.3pd
- [x] Step 6) A summary is formatted into a table like the one at the top [here](https://github.com/adoptium/temurin-build/issues/3482).
  - 2-4ph: Write initial code to generate md table.
  - 1-3ph: Fix bugs.
  - 1ph: Output table to file.
  - 1-4ph: Test output works and is accurate.
  - 0.5-2pd: Approximate Total.
  - Actual time: 0.2pd
    - Note: The table doesn't seem as useful as a simple number, which is what the community asked for upstream.
- [x] Step 7) All of the information (the link to the job, the useful output, and the metadata) then gets put after the table, in chunks.
  - 1-3ph: Write code and test. This *should* be simple.
  - Actual time: 1.5ph: It was, barring a single bug that's been fixed.
- [x] Step 8) The summary and the full info list are then output from the script, where the GitHub Action collects them.
- [x] Step 9) The action finally creates a build triage issue in the same repository, with the script output as the issue's contents.
- [x] ~~Step 10) Cake.~~
  - Cancelled this for diet's sake. 😞

### PR DESCRIPTION
**Pull request by adamfarley**
Adds the logic and list of regexes that are used to determine the likely cause of a build's failure/aborted state.

Also identifies the likely cause of each failure, as well as whether it could have been prevented, and presents that information in a new git issue.

Example run here: https://github.com/adamfarley/temurin-build/actions/runs/7195461176

Example issue here: https://github.com/adamfarley/temurin-build/issues/35

Resolves #3521

### CODE REVIEW

**Comment by adamfarley** [comment]
Resolving the linter failures now.

Note: It's weird that the linter displays the wrong PR number at the top: https://github.com/adoptium/temurin-build/actions/runs/7209034140/job/19639180944#logs

Thoughts:
- Maybe that's not the PR number. 
- What could \#3343 be?
- It's too short to be a commit ID. 
- That's definitely the PR's title, so I'd assume it should be the PR number.

**Comment by adamfarley** [comment]
The build failures cannot be related to this change because the build auto-triage scripts are not part of the build process.

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by sxa — APPROVED** [review]
Approving based on the demo last week and the runs listed in the description which seemed to work. I have no done a full review of the code, but that can be revised later

**Pull request merged**
