### PR TITLE
Force use of Dragonwell 8 boot JDK for building itself

### PR DESCRIPTION
**Pull request by sxa**
I'm not really comfortable with downloading a boot JDK from a third party site during the build process for the boot JDK but since the two platforms it affects are built by us in disposable docker containers I'm less concerned... This change leaves the door open for an option of adding it to the playbooks too

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by karianna** [comment]
Do we know why an Alibaba JVM is required as the boot JVM?  That seems a little odd given Java Spec.

**Comment by sxa** [comment]
> 

I have not investigated that.

> Do we know why an Alibaba JVM is required as the boot JVM? That seems a little odd given Java Spec.

No I have no investigated that, although I think OpenJ9 at one point had to be bootstrapped with OpenJ9 in certain circumstances, so it's not something that surprises me.

**Comment by karianna** [comment]
@sxa is this needed for the release?

**Comment by sxa** [comment]
> @sxa is this needed for the release?

We do not ship Dragonwell as a release from Adoptium, therefore no.

**Review by karianna — APPROVED** [review]
LGTM

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by joeyleeeeeee97** [comment]
Hi, could we merge this? https://github.com/adoptium/temurin-build/pull/2912 depends on this.

Thanks

**Comment by karianna** [comment]
run tests

**Comment by karianna** [comment]
@sxa I can'y see to rerun the GH Action or edit your PR, are you able to recreate?

**Comment by sxa** [comment]
Have force pushed a commit message change which will re-run ... Not sure why we couldn't just re-run the actions on this one ...

**Comment by sxa** [comment]
Windows failure appears unrelated to this PR:
```
  Initialized empty Git repository in /cygdrive/d/a/temurin-build/temurin-build/.git/
  C:\cygwin64\bin\git.exe remote add origin https://github.com/adoptium/temurin-build
  Error: fatal: unsafe repository ('/cygdrive/d/a/temurin-build/temurin-build' is owned by someone else)
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /cygdrive/d/a/temurin-build/temurin-build
  Error: The process 'C:\cygwin64\bin\git.exe' failed with exit code 128
```

**Comment by sxa** [comment]
Verifying at https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2114/ which is running the following dragonwell jobs:
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-dragonwell/431/consoleFull
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-dragonwell/281/consoleFull
Both built successfully.

**Pull request merged**
