### PR TITLE
Fix incorrect jdkbinary JDK folder directory when run from Rebuild_Same_JDK_Reproducibility_Test

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
When linux_repro_build_compare.sh was called from aqa-tests passing the jdkbinary folder it was comparing the top-level jdkbinary folder containing all the artifacts (jdk,jre,static-libs,..) rather than the jdk-VERSION folder...

Slightly complicated by the fact that TKG calls using the expanded "all artifacts" top directory (jdkbinary), whereas a "user" might expect to call using a local reference to the jdk-V.0.M+B folder. I've updated the script to assume the when
a local directory is used it references the folder that contains the jdk-V.0.M+B folder specified in the SBOM.

Grinder test: https://ci.adoptium.net/job/Grinder/11309/

### CODE REVIEW

**Review by steelhead31 — APPROVED** [review]
Looks ok.

**Review by sxa — COMMENTED** [review]
Not approving yet as the Grinder doesn't look to have been successful:
```
17:16:08  Number of differences: 432
17:16:08  ./repro_compare.sh: line 77: (files1-num_differences)*100*100/files1 : division by 0 (error token is "files1 ")
17:16:08  ReproduciblePercent = 0. %
17:16:08  Differences found..., logged in: reprotest.diff
17:16:29  -----------------------------------
17:16:29  Rebuild_Same_JDK_Reproducibility_Test_0_FAILED
17:16:29  -----------------------------------
```

**Comment by andrew-m-leonard** [comment]
mmm something else not right!

**Review by karianna — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
so I was wrong! I misstook the jdk-21.0.6+2 folder for what I thought was the JDK, it was in fact a different archive(debug image artifact), along side also the static-libs folder which is getting placed in j2sdk-image, ref: https://adoptium.slack.com/archives/C09NW3L2J/p1731420319899309?thread_ts=1731417632.215039&cid=C09NW3L2J
I'm going to resolve the issue hopefully in https://github.com/adoptium/aqa-tests/blob/master/get.sh#L451
so jdkbinary is correctly and logically populated as intended

**Comment by andrew-m-leonard** [comment]
Will be fixed by https://github.com/adoptium/aqa-tests/issues/5749

**Pull request closed without merging**
