### PR TITLE
Enable reproducible comparing tests on jdk21+ macos

### PR DESCRIPTION
**Pull request by sophia-guo**
Depends https://github.com/adoptium/ci-jenkins-pipelines/pull/1136

https://github.com/adoptium/temurin-build/pull/4026

### CODE REVIEW

**Comment by sophia-guo** [comment]
I have tried both static mac and orka. Both no jq installed.

https://ci.adoptium.net/view/Test_grinder/job/Grinder/10327/console
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10328

```
Error: jq is not installed. Please install jq before running this script
```

Might be easy to install jq on static mac and orka?

**Comment by sophia-guo** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10427/

**Comment by steelhead31** [comment]
> https://ci.adoptium.net/view/Test_grinder/job/Grinder/10427/
> 
> ```
> 17:21:04  Xcode 10.3
> 17:21:04  Build version 10G8
> 17:21:04  Xcode Build Success - Get Version
> 17:21:04  ERROR - No Xcode Installation Matching 15.2 Could Be Identified
> ```
> 
> Does this mean we can't do reproducing on this environment https://ci.adoptium.net/computer/test-macstadium-macos1014-x64-1/ due to the Xcode version not matching. @steelhead31 ?

Yup, that machines OS I think is too old for Xcode 15.2, and I think it has to be the same version of Xcode for reproducibility to work, @andrew-m-leonard can confirm this I think :)

**Comment by andrew-m-leonard** [comment]
> > https://ci.adoptium.net/view/Test_grinder/job/Grinder/10427/
> > ```
> > 17:21:04  Xcode 10.3
> > 17:21:04  Build version 10G8
> > 17:21:04  Xcode Build Success - Get Version
> > 17:21:04  ERROR - No Xcode Installation Matching 15.2 Could Be Identified
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does this mean we can't do reproducing on this environment https://ci.adoptium.net/computer/test-macstadium-macos1014-x64-1/ due to the Xcode version not matching. @steelhead31 ?
> 
> Yup, that machines OS I think is too old for Xcode 15.2, and I think it has to be the same version of Xcode for reproducibility to work, @andrew-m-leonard can confirm this I think :)

Yes, correct Xcode 15.2 requires MacOS 13.5 minimum : https://developer.apple.com/support/xcode/

**Comment by sophia-guo** [comment]
So we  need extra label for macos to ensure the reproducing tests run on correct environment. Ether xcode15.2 or sw.os.osx.13_5.  Two Mac static agents wont work for reproducing tests. https://ci.adoptium.net/label/ci.role.test&&hw.arch.x86&&%28sw.os.osx%7C%7Csw.os.mac%29/

Current orka ones are label as [xcode15.0.1&&build&&mac&&x64](https://ci.adoptium.net/label/xcode15.0.1&&build&&mac&&x64/) so can't work for reproducing either. Should we open an issue in infra to see if it's possible to update orka's os version?

**Comment by sophia-guo** [comment]
Interesting orka ones with label `xcode15.0.1&&build&&mac&&x64` can do the reproducing build. https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-mac-x64-temurin/146/ https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-mac-x64-temurin/146/artifact/workspace/target/OpenJDK21U-sbom_x64_mac_hotspot_2024-05-31-22-18.json

**Comment by andrew-m-leonard** [comment]
> Interesting orka ones with label `xcode15.0.1&&build&&mac&&x64` can do the reproducing build. https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-mac-x64-temurin/146/ https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-mac-x64-temurin/146/artifact/workspace/target/OpenJDK21U-sbom_x64_mac_hotspot_2024-05-31-22-18.json

@sophia-guo so the Orka nodes are using Xcode 15.2, the 15.0.1 label has not been changed just because of the hassle involved! should have been called Xcode15 !

**Comment by sophia-guo** [comment]
```
16:32:23  Make JDK Any Platform Argument List = 
16:32:23  --clean-git-repo --jdk-boot-dir /Users/admin/comp-jdk-build/jdk-20.0.2+9/Contents/Home --target-file-name OpenJDK21U-jdk_x64_mac_hotspot_21.0.4_5-ea.tar.gz --disable-shallow-git-clone -bjdk-21.0.4+5_adopt --create-jre-image --create-sbom --build-reproducible-date "2024-06-25 11:04:23"--user-openjdk-build-root-directory /Users/admin/comp-jdk-build/temurin-build/workspace/build/openjdkbuild/ --freetype-dir bundled --use-jep319-certs --create-debug-image  --configure-args "--disable-warnings-as-errors --openjdk-target=x86_64-apple-darwin --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --with-extra-cxxflags='-mmacosx-version-min=10.9' --enable-dtrace --with-version-opt=ea"" --build-variant temurin jdk21u 
16:32:23  
16:32:23  Parameters Parsed Successfully
16:32:23  ---------------------------------------------
16:32:23  Building JDK...
16:32:23  sh: line 1: unexpected EOF while looking for matching `"'
16:32:23  sh: line 2: syntax error: unexpected end of file
16:32:23  -----------------------------------
16:32:23  Rebuild_Same_JDK_Reproducibility_Test_Mac_0_FAILED
```

parsing issue as SBOM --configure-args value format updated with double quotes. Parsing in mac script also need to update.

**Comment by sophia-guo** [comment]
New grinder with latest

https://ci.adoptium.net/view/Test_grinder/job/Grinder/10764/

**Comment by sophia-guo** [comment]
Running with orka, issue message complains the Xcode can't be found.
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10771/console

```
11:27:51  Compiler Version Returned From SBOM: clang (clang/LLVM from Xcode 15.2)
11:27:51  Checking For Xcode Compilers In : /Applications/
11:27:51  Error - An Xcode Installaton Could Not Be Found In The Default Path : /Applications / Xcode 
11:27:51  -----------------------------------
11:27:51  Rebuild_Same_JDK_Reproducibility_Test_Mac_0_FAILED
```

**Comment by sophia-guo** [comment]
@steelhead31 If it's related with how the Xcode installation is checked? https://github.com/adoptium/temurin-build/pull/3844#issuecomment-2178754616

**Comment by sophia-guo** [comment]
rerun on build orka node https://ci.adoptium.net/label/xcode15.0.1&&build&&mac&&x64/ got different error from running on test orka node https://ci.adoptium.net/label/ci.role.test&&sw.os.osx&&orka&&hw.arch.x86/

https://ci.adoptium.net/view/Test_grinder/job/Grinder/10775/console

```
12:01:08  ---------------------------------------------
12:01:08  Building JDK...
12:01:08  sh: line 1: unexpected EOF while looking for matching `"'
12:01:08  sh: line 2: syntax error: unexpected end of file
12:01:08  -----------------------------------
12:01:08  Rebuild_Same_JDK_Reproducibility_Test_Mac_0_FAILED
12:01:08  -----------------------------------
```

**Comment by steelhead31** [comment]
@sophia-guo I've put some debugging in, and it does appear the script is checking correctly, but not finding an Xcode installation on that Orka node..  
  
`00:02:46.365  ---------------------------------------------`  
`00:02:46.365  System Architecture: 64-bit (Intel)`  
`00:02:46.365  SBOM & SYSTEM Architectures Match - All OK`  
`00:02:46.365  ---------------------------------------------`  
`00:02:46.365  Checking For Supported Compiler Versions...`  
`00:02:46.365`   
`00:02:46.365  Compiler Version Returned From SBOM: clang (clang/LLVM from Xcode 15.2)`  
`00:02:46.366  Checking For Xcode Compilers In : /Applications/`  
`00:02:46.366  Debug Xcode Find`  
`00:02:46.366  total 0`  
`00:02:46.366  drwxr-xr-x  3 root  wheel  96 Oct 20  2023 Utilities`  
`00:02:46.366  lrwxr-xr-x@ 1 root  wheel  54 Oct 20  2023 Safari.app -> ../System/Cryptexes/App/System/Applications/Safari.app`  
`00:02:46.366  drwxr-xr-x  3 root  wheel  96 Jul 10 03:52 Packages.app`  
`00:02:46.366  End Debug`  
`00:02:46.366  Error - An Xcode Installaton Could Not Be Found In The Default Path : /Applications / Xcode`

**Comment by steelhead31** [comment]
@sophia-guo I've run a grinder here [https://ci.adoptium.net/view/Test_grinder/job/Grinder/10782/console](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10782/console) with these labels.. ( borrowed from a build job )  
  
`xcode15.0.1&&build&&mac&&x64&&!build-orka-macos14-arm64-fwc8f`  
 

So this issue is down to the orka test nodes not having Xcode installed... I'll take a look at the other issue now

**Comment by steelhead31** [comment]
@sophia-guo I've fixed the issue with the repro script, and it now attempts to build, but its complaining about a missing SPEC.mk file.. 

`Error: Cannot locate spec.gmk, given by SPEC=osx_x86-64.`

@andrew-m-leonard may also be able to help in my absence.

**Comment by sophia-guo** [comment]
@steelhead31 so it does mean orka test nodes   https://ci.adoptium.net/label/xcode15.0.1&&build&&mac&&x64/  are configured different from orka build nodes https://ci.adoptium.net/label/ci.role.test&&sw.os.osx&&orka&&hw.arch.x86/ ? So we will need to open an infra issue to have orka test nodes installed right xcode.

**Comment by sophia-guo** [comment]
There are xcode related check error message even with build orka node.   Are those the reasons of the failure build?


https://ci.adoptium.net/view/Test_grinder/job/Grinder/10775/console

```
12:00:59  Compiler Version Returned From SBOM: clang (clang/LLVM from Xcode 15.2)
12:00:59  Checking For Xcode Compilers In : /Applications/
12:00:59  At Least One Xcode Installation Was Found ... Checking Versions
12:00:59  Current User Can Use Xcode Select... Continuing
12:00:59  Checking Path ... /Applications/Xcode.app
12:00:59  Xcode 15.2
12:00:59  Build version 15C500b
12:00:59  Xcode Build Success - Get Version
12:00:59  Checking Path ... /Applications/Xcode-11.7.app
12:00:59  xcrun: error: unable to load libxcrun (dlopen(/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (no such file), '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
12:00:59  The Xcode Build Version For The Xcode Installation In /Applications/Xcode-11.7.app Could Not Be Obtained
12:00:59  Installed clang version: 15.0.0
```

**Comment by steelhead31** [comment]
> There are xcode related check error message even with build orka node. Are those the reasons of the failure build?
> 
> https://ci.adoptium.net/view/Test_grinder/job/Grinder/10775/console
> 
> ```
> 12:00:59  Compiler Version Returned From SBOM: clang (clang/LLVM from Xcode 15.2)
> 12:00:59  Checking For Xcode Compilers In : /Applications/
> 12:00:59  At Least One Xcode Installation Was Found ... Checking Versions
> 12:00:59  Current User Can Use Xcode Select... Continuing
> 12:00:59  Checking Path ... /Applications/Xcode.app
> 12:00:59  Xcode 15.2
> 12:00:59  Build version 15C500b
> 12:00:59  Xcode Build Success - Get Version
> 12:00:59  Checking Path ... /Applications/Xcode-11.7.app
> 12:00:59  xcrun: error: unable to load libxcrun (dlopen(/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (no such file), '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
> 12:00:59  The Xcode Build Version For The Xcode Installation In /Applications/Xcode-11.7.app Could Not Be Obtained
> 12:00:59  Installed clang version: 15.0.0
> ```

Yes, they can be ignored, in addition to the xcode15.2 there is also an old Xcode11.7 installation, the script attempts to check the version and fails, but then switches to the correct 15.2 version, I'll see if I can tidy up the output, but its safe to ignore in the meantime.

**Comment by sophia-guo** [comment]
> https://github.com/adoptium/temurin-build/pull/3844#issuecomment-2301718863

Just realized it's rebuilding x64mac on aarch64mac if using build label https://ci.adoptium.net/label/xcode15.0.1&&build&&mac&&x64/ , not sure if that's the reason for themissing SPEC.mk file? 

https://github.com/adoptium/infrastructure/issues/3720#issuecomment-2302739570

**Comment by sophia-guo** [comment]
> @sophia-guo I've fixed the issue with the repro script, and it now attempts to build, but its complaining about a missing SPEC.mk file..

@steelhead31 what's the fix? I did some force push and lost the changes you did, could you redo it so I can do a rebase?

@andrew-m-leonard any idea about the  `missing spec.mk file` error? The original jdk is mac-x64 jdk( build on aarch64 ) the reproduced jdk is also mac-x64 ( build on  aarch64). test mac doesn't have xcode installed https://github.com/adoptium/infrastructure/issues/3720.  I'm not sure if https://github.com/adoptium/temurin-build/pull/3923 fixed this issue, as I lost the changes of @steelhead31 and can't rerun build to get this issue yet.

```
13:46:45  Error: Cannot locate spec.gmk, given by SPEC=osx_x86-64.
13:46:45  /Users/admin/comp-jdk-build/temurin-build/workspace/build/src/make/Init.gmk:124: *** Cannot continue.  Stop.
13:46:45  OpenJDK make failed, archiving make failed logs
13:46:45  Archiving and compressing with gzip
13:46:45  
13:46:45  real	0m0.003s
13:46:45  user	0m0.001s
13:46:45  sys	0m0.002s
```
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10791/console

Another question @andrew-m-leonard would be for mac64 build from temurin ( on aarch64) reproduced comparing jdk should be built on x64 or aarch64? Or it doesn't matter there should be no difference. @sxa has the same question https://github.com/adoptium/infrastructure/issues/3720#issuecomment-2302465182

**Comment by andrew-m-leonard** [comment]
@sophia-guo it's not clear what's wrong there, it's building on a mac arm64 node, so that is good. The "configure" has completed successfully, so it must be the "make" step that is failing, will need some extra debug there to work out why

**Comment by andrew-m-leonard** [comment]
@sophia-guo The problem I think is due to the TKG setting the "SPEC" make variable. I can see from the https://github.com/adoptium/temurin-build/blob/fdeec626b28bff63a2ae55df59d445361db0753a/test/system/reproducibleCompare/reproducible.mk#L20 that it looks at a "SPEC" variable, within the make environment.
We need to ensure SPEC is "unset" before calling the mac repro compare build....

If I try this I get the same error:
```
anleonar@anleonar-mac macosx-aarch64-server-release % make images SPEC=asdfasf
Error: Cannot locate spec.gmk, given by SPEC=asdfasf.
/Users/anleonar/workspace/temurin-build/workspace/build/src/make/Init.gmk:124: *** Cannot continue.  Stop.
```

**Comment by sophia-guo** [comment]
I have updated the parsing of makejdk_any_platform_args to align with linux. It seems no issue with the arguments. but I got 

```
14:01:15  BUILD_CONFIG[WORKSPACE_DIR]="/Users/admin/comp-jdk-build/temurin-build/workspace"
14:01:15  /Users/admin/comp-jdk-build/temurin-build/sbin/build.sh: line 1968: cd: /Users/admin/comp-jdk-build/temurin-build/workspace/./build//src: No such file or directory
14:01:15  fatal: '/Users/admin/comp-jdk-build/temurin-build/workspace/./build//src' does not appear to be a git repository
14:01:15  fatal: Could not read from remote repository.
14:01:15 
```
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10836/consoleFull

@andrew-m-leonard any idea about this? I haven't tried to reset SPEC, if reset what should be the correct value SPEC=osx_aarch64 for cross compiling?

**Comment by andrew-m-leonard** [comment]
> I have updated the parsing of makejdk_any_platform_args to align with linux. It seems no issue with the arguments. but I got
> 
> ```
> 14:01:15  BUILD_CONFIG[WORKSPACE_DIR]="/Users/admin/comp-jdk-build/temurin-build/workspace"
> 14:01:15  /Users/admin/comp-jdk-build/temurin-build/sbin/build.sh: line 1968: cd: /Users/admin/comp-jdk-build/temurin-build/workspace/./build//src: No such file or directory
> 14:01:15  fatal: '/Users/admin/comp-jdk-build/temurin-build/workspace/./build//src' does not appear to be a git repository
> 14:01:15  fatal: Could not read from remote repository.
> 14:01:15 
> ```
> 
> https://ci.adoptium.net/view/Test_grinder/job/Grinder/10836/consoleFull
> 
> @andrew-m-leonard any idea about this? I haven't tried to reset SPEC, if reset what should be the correct value SPEC=osx_aarch64 for cross compiling?

For an OpenJDK make, SPEC is not set, so in reproducible.mk trying unsetting it ?

**Comment by sophia-guo** [comment]
@andrew-m-leonard what should we do with option  `--assemble-exploded-image` on mac? Can we just ignore it?

**Comment by sophia-guo** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10922/console @andrew-m-leonard 

Regarding to run this x64 tests on arm64, I haven't got a good solution for this. Right now we can enable as part of dev.system and set a special rule like dev.system on mac only run on arm64, as there is no other tests in this group right now. But going forward this is not correct.

**Comment by andrew-m-leonard** [comment]
> https://ci.adoptium.net/view/Test_grinder/job/Grinder/10922/console @andrew-m-leonard . This is the results by reproduced on arm64 by comparing with repro_compare.sh. Anything wrong?
> 
> Regarding to run this x64 tests on arm64, I haven't got a good solution for this. Right now we can enable as part of dev.system and set a special rule like dev.system on mac only run on arm64, as there is no other tests in this group right now. But going forward this is not correct.

@sophia-guo It looks like it's not picking up a good JDK for running the Java compare classes:
```
18:31:20  Cleaning any Temurin build-scripts release file BUILD_INFO from src_jdk/Contents/Home
18:31:21  Error: Fatal error: Unsupported class file version: 67
```

**Comment by sophia-guo** [comment]
> @sophia-guo It looks like it's not picking up a good JDK for running the Java compare classes:

@andrew-m-leonard I don't quite understand this. Source jdk is copied from build https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk23/job/jdk23-mac-x64-temurin/16/artifact/workspace/target/OpenJDK23U-jdk_x64_mac_hotspot_23_37-ea.tar.gz. We can successfully rebuild the compared one. Both have this issue `Error: Fatal error: Unsupported class file version: 67`

But the compare results is exactly same as when we use the independent jenkins job (thought it's jdk21) https://ci.adoptium.net/view/ReproducibleBuild/job/jdk21u-mac-x64-temurin_reproduce_compare/74/consoleFull

So I'm thinking this might not be issues from test view?

**Comment by andrew-m-leonard** [comment]
> > @sophia-guo It looks like it's not picking up a good JDK for running the Java compare classes:
> 
> @andrew-m-leonard I don't quite understand this. Source jdk is copied from build https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk23/job/jdk23-mac-x64-temurin/16/artifact/workspace/target/OpenJDK23U-jdk_x64_mac_hotspot_23_37-ea.tar.gz. We can successfully rebuild the compared one. Both have this issue `Error: Fatal error: Unsupported class file version: 67`
> 
> But the compare results is exactly same as when we use the independent jenkins job (thought it's jdk21) https://ci.adoptium.net/view/ReproducibleBuild/job/jdk21u-mac-x64-temurin_reproduce_compare/74/consoleFull
> 
> So I'm thinking this might not be issues from test view?

The problem is occuring invoking "javap" to process the System*.class files, here: https://github.com/adoptium/temurin-build/blob/13b306f924ca0a599686140d3b893fd902fca732/tooling/reproducible/repro_common.sh#L104
The System*.class will be compiled with the given JDK internal class version, so for jdk-23 that is "67". I would guess the "javap" being picked up off PATH by the test is not jdk-23, so it will not know how to read a jdk-23(67) class file.
The reason it works for jdk21u is probably because the test is picking up a jdk-21 jdk in the PATH?

To resolve, I think we need to put a copy of the source or target JDK in the PATH, to resolve ot a version of "javap" that knows how to process class files of the same internal version.

**Comment by sophia-guo** [comment]
For cross compiling issue discussion is here https://github.com/adoptium/TKG/issues/618

**Comment by sophia-guo** [comment]
Enable aarch64_mac https://ci.adoptium.net/view/Test_grinder/job/Grinder/11044/

**Comment by sophia-guo** [comment]
Update all javap with testJDK. 

Also there are 150 dylib differences, which seems removeMacOSNonComparableData() ( remove the macos dylib non-compararable data) was not called at all. Updated to call removeMacOSNonComparableData() and removeWindowsNonComparableData() before the final patchManifests step. 

@andrew-m-leonard removeMacOSNonComparableData() get the error, what's the issue here?

```
00:18:25  Removing MacOS dylib non-comparable UUID from src_jdk/Contents/Home
00:18:45  Error occurred during initialization of VM
00:18:45  Failed setting boot class path.
00:18:45    FAILED ==> java "temurin.tools.BinRepl" --inFile "src_jdk/Contents/Home/../../Contents/Home/bin/jwebserver" --outFile "src_jdk/Contents/Home/../../Contents/Home/bin/jwebserver" --hex "8C:04:09:F5:4F:35:3A:EB:B0:C1:42:BF:D8:09:D4:D5-AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA" --firstOnly
```
https://ci.adoptium.net/view/Test_grinder/job/Grinder/11059/console

**Comment by sophia-guo** [comment]
New failures with "${JDK_DIR}"/bin/javap -v -sysinfo -l -p -c -s -constants "$ff" > "$f.javap.tmp" 
and "${JDK_DIR}"/bin/javap -v -sysinfo -l -p -c -s -constants "$ff" > "$f.javap.tmp"

https://ci.adoptium.net/view/Test_grinder/job/Grinder/11137/console
```
./repro_common.sh: line 97: 45700 Killed: 9               "${JDK_DIR}"/bin/javap -v -sysinfo -l -p -c -s -constants "$ff" > "$f.javap.tmp"
```

**Comment by sophia-guo** [comment]
One question is if it is  reproducible and comparable between cross-compiled x64 mac64 and native x64 mac. I've tried locally with xcode 16.1.  Using sbom file generated by cross-compiled x64 mac64 . Got following failures, @andrew-m-leonard do you think the failure is caused by using cross-compiled x64 mac64 with aarch64 to compile on x64?


```
[buildjdk] Creating buildjdk/support/modules_libs/java.base/libsyslookup.dylib from 1 file(s)

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libfreetype/static/libfreetype.a(ftdbgmem.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libfreetype/static/libfreetype.a(ftmac.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libfreetype/static/libfreetype.a(pngshim.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libfreetype/static/libfreetype.a(sfwoff.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libfreetype/static/libfreetype.a(sfwoff2.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libfreetype/static/libfreetype.a(ttsubpix.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libfreetype/static/libfreetype.a(woff2tags.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libawt/static/libawt.a(debug_assert.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libawt/static/libawt.a(debug_mem.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libawt/static/libawt.a(debug_util.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/liblcms/static/liblcms.a(cmshalf.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/native/java.desktop/libfontmanager/static/libfontmanager.a(hb-static.o) has no symbols

[buildjdk] Creating buildjdk/support/modules_cmds/java.base/java from 1 file(s)

[buildjdk] Creating buildjdk/support/modules_cmds/java.base/keytool from 1 file(s)

[buildjdk] Creating buildjdk/support/modules_libs/java.base/jspawnhelper from 1 file(s)

[buildjdk] Creating buildjdk/support/modules_cmds/jdk.jlink/jimage from 1 file(s)

[buildjdk] Creating buildjdk/support/modules_cmds/jdk.jdeps/javap from 1 file(s)

[buildjdk] Creating buildjdk/support/modules_cmds/jdk.jlink/jlink from 1 file(s)

[buildjdk] Creating buildjdk/support/modules_cmds/jdk.jdeps/jdeps from 1 file(s)

[buildjdk] Creating buildjdk/support/modules_cmds/jdk.jlink/jmod from 1 file(s)

[buildjdk] Creating buildjdk/support/modules_cmds/jdk.jdeps/jdeprscan from 1 file(s)

[buildjdk] Creating interim java.logging.jmod

[buildjdk] Creating interim java.base.jmod

Exception in thread "main" java.lang.ClassFormatError: StackMapTable format error: bad verification type

	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)

make[4]: *** [/Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/interim-jmods/support/_create_java.logging.jmod_exec.marker] Error 1

make[3]: *** [java.logging-interim-jmod] Error 2

make[3]: *** Waiting for unfinished jobs....

Exception in thread "main" java.lang.ClassFormatError: StackMapTable format error: bad verification type

	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)

make[4]: *** [/Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/support/interim-jmods/support/_create_java.base.jmod_exec.marker] Error 1

make[3]: *** [java.base-interim-jmod] Error 2

make[2]: *** [create-buildjdk-interim-image] Error 2

make[2]: *** Waiting for unfinished jobs....



ERROR: Build failed for targets 'product-images mac-legacy-jre-bundle test-image static-libs-image' in configuration 'macosx-x86_64-server-release' (exit code 2) 



=== Output from failing command(s) repeated here ===

* For target support_interim-jmods_support__create_java.base.jmod_exec:

Exception in thread "main" java.lang.ClassFormatError: StackMapTable format error: bad verification type

	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)

* For target support_interim-jmods_support__create_java.logging.jmod_exec:

Exception in thread "main" java.lang.ClassFormatError: StackMapTable format error: bad verification type

	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)



* All command lines available in /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/make-support/failure-logs.

=== End of repeated output ===



No indication of failed target found.

HELP: Try searching the build log for '] Error'.

HELP: Run 'make doctor' to diagnose build problems.



make[1]: *** [main] Error 2

make: *** [product-images] Error 2

OpenJDK make failed, archiving make failed logs

Copying build.log to TemurinLogsArchive

Copying make-support/failure-logs to TemurinLogsArchive

Archiving and compressing with pigz



real	0m0.511s

user	0m0.005s

sys	0m0.007s

Your archive was created as /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/build/src/build/macosx-x86_64-server-release/OpenJDK.tar.gz

Moving the artifact to location /Users/sophia/DevelopTest/git/temurin-build/tooling/reproducible/comp-jdk-build/temurin-build/workspace/target//OpenJDK21U-makefailurelogs_x64_mac_hotspot_21.0.5_11.tar.gz

archive done.

Failed to make the JDK, exiting
```

**Comment by andrew-m-leonard** [comment]
> One question is if it is reproducible and comparable between cross-compiled x64 mac64 and native x64 mac. I've tried locally with xcode 16.1. Using sbom file generated by cross-compiled x64 mac64 . Got following failures, @andrew-m-leonard do you think the failure is caused by using cross-compiled x64 mac64 with aarch64 to compile on x64?

@sophia-guo mmm not sure, however it maybe Xcode 16.1 issue, as we currently build using Xcode 15.2

**Comment by sophia-guo** [comment]
I've installed xcode 15.2 instead of 16.1.  Using cross-compiled x64 mac jdk on arm64 mac SBOM  https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%2B11/OpenJDK21U-sbom_x64_linux_hotspot_21.0.5_11.json did reproducing on my local x64 mac and did a compare. Result shows except the dylib differences ( known issue https://github.com/adoptium/temurin-build/issues/3989) it's indentical.

```
Files /Users/sophia/DevelopTest/git/src_jdk/Contents/Home/lib/server/libjsig.dylib and /Users/sophia/DevelopTest/git/tar_jdk/Contents/Home/lib/server/libjsig.dylib differ
Files /Users/sophia/DevelopTest/git/src_jdk/Contents/Home/lib/server/libjvm.dylib and /Users/sophia/DevelopTest/git/tar_jdk/Contents/Home/lib/server/libjvm.dylib differ
Number of differences:      146
ReproduciblePercent = 99.86 %
```

So go back to initial question if it makes sense to do the reproduce a cross compiled x64 mac on aarch64 and compare with native complied jdk on x64 mac?

> Another question @andrew-m-leonard would be for mac64 build from temurin ( on aarch64) reproduced comparing jdk should be built on x64 or aarch64? Or it doesn't matter there should be no difference. @sxa has the same question https://github.com/adoptium/infrastructure/issues/3720#issuecomment-2302465182

**Comment by andrew-m-leonard** [comment]
i'd hope make no difference, but we'd need to check

**Comment by sophia-guo** [comment]
With https://github.com/adoptium/temurin-build/issues/4025 x64 mac reproducible  can be enabled on aarch64 mac

**Comment by sophia-guo** [comment]
Temporarily enable on macx64 https://github.com/adoptium/ci-jenkins-pipelines/pull/1136

**Review by smlambert — APPROVED** [review]

**Review by andrew-m-leonard — APPROVED** [review]

**Pull request merged**
