### PR TITLE
Enable reproducable comparation in aqa-tests on windows

### LINKED ISSUE #3711: Add reproducible comparison tests on windows
Issues:

- [x] https://github.com/adoptium/infrastructure/issues/3453
- [x] Auto trigger by upstream( beta-trigger) , figure out the jdk and sbom file - adding reproducible.mk
- [x] workdir doesn't work with jenkins user,
- [x] install apt-cygwin - no permission @steelhead31 if apt-cygwin is must we will have to ask infra to install it on the jenkins agents?
- [x] Invalid build.sh option: --with-version-opt 
- [x] configure: error: Your base path is too long. It is 170 characters long, but only 100 is supported. 
- [ ] Error: Cannot locate spec.gmk, given by SPEC=win_x86-64. https://github.com/adoptium/temurin-build/issues/3711#issuecomment-2025880943

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix #3711

### CODE REVIEW

**Comment by sophia-guo** [comment]
Using release build https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk22u/job/jdk22u-release-windows-x64-temurin/7/

Grinder https://ci.adoptium.net/view/Test_grinder/job/Grinder/9826/console

```
14:47:48  checkoutRequiredCodeToBuild:
14:47:48    workspace = /cygdrive/c/comp-jdk-build/temurin-build/workspace/./build//src
14:47:48    BUILD_VARIANT = hotspot
14:47:48    TAG = jdk-22.0.1+8_adopt
14:47:48    BRANCH = master
14:47:50  tree d1e46c26a3dc0030e6adc02f7283fc4729ec5b91
14:47:50  parent b2fbc8283e3f948ae01eb0792c46854c796565b8
14:47:50  author Aleksey Shipilev <shade@openjdk.org> 1714406553 +0000
14:47:50  committer Aleksey Shipilev <shade@openjdk.org> 1714406553 +0000
14:47:50  
14:47:50  8324121: SIGFPE in PhaseIdealLoop::extract_long_range_checks
14:47:50  8329163: C2: possible overflow in PhaseIdealLoop::extract_long_range_checks()
14:47:50  
14:47:50  Backport-of: cb2a6713596548d76c03912709656172b0bbcc76
14:47:50  look like the scm ref given is a valid sha, so treat it as a sha
14:47:50  Checking out tag jdk-22.0.1+8_adopt
14:47:50  fatal: couldn't find remote ref refs/tags/jdk-22.0.1+8_adopt
```

Console of release build

```
05:03:13  checkoutRequiredCodeToBuild:
05:03:13    workspace = /cygdrive/c/workspace/openjdk-build/workspace/./build//src
05:03:13    BUILD_VARIANT = temurin
05:03:13    TAG = jdk-22.0.1+8_adopt
05:03:13    BRANCH = dev
05:03:15  fatal: Not a valid object name dev
05:03:15  Checking out tag jdk-22.0.1+8_adopt
05:03:28  Note: switching to 'jdk-22.0.1+8_adopt'.
```

**Comment by sophia-guo** [comment]
Opts after C:/workspace/openjdk-build/workspace/build/openjdkbuild--freetype-dir bundled can't be parsed. Seems parse problem as there is space missing `C:/workspace/openjdk-build/workspace/build/openjdkbuild--freetype-dir` before option `--freetype-dir`

**Comment by sophia-guo** [comment]
Also the other parser also feels not good

```
--with-ucrt-dll-dir=temporary_speech_mark_placeholderC:/PROGRA~2/WI3CF2~1/10/Redist/100226~1.0/ucrt/DLLs/x64temporary_speech_mark_placeholder
```

**Comment by sophia-guo** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9837/console

https://ci.adoptium.net/computer/test-azure-win2022-x64-3/

```
17:51:45  Checking Visual Studio Version Retrieved From SBOM : microsoft (Microsoft Visual Studio 2022)
17:51:45  Visual Studio Version: 2022
17:51:45  Visual Studio Base Path = /cygdrive/c/Program Files/Microsoft Visual Studio/2022
17:51:45  
17:51:45  Checking For C & C++ VS Compilers In : /cygdrive/c/Program Files/Microsoft Visual Studio/2022/
17:51:49  Found C Compiler : /cygdrive/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe : Version : 19.37.32822
17:51:49  Found C++ Compiler : /cygdrive/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe : Version : 19.37.32822
17:51:49  ---------------------------------------------
17:51:52  ---------------------------------------------
17:51:52  No Match - Set To Derived Version
17:51:52  REQ UCRT = 10.0.22621.1778 (WinBuild.160101.0800)
17:51:52  Check For UCRT DLL In : C:/Program Files (x86)/Windows Kits/10/Redist
17:51:55  ERROR - A Version Of ucrtbase.dll matching 10.0.22621.1778 (WinBuild.160101.0800)
 was not found on this system - Exiting
17:51:55  -----------------------------------
17:51:55  Rebuild_Same_JDK_Reproducibility_Test_win_0_FAILED
```

**Comment by sophia-guo** [comment]
https://ci.adoptium.net/computer/test-azure-win2022-x64-1/ no jq installed.

https://ci.adoptium.net/view/Test_grinder/job/Grinder/9862/

https://ci.adoptium.net/computer/test-azure-win2022-x64-3/ - WIN_URCT_BASE="C:/Program Files (x86)/Windows Kits/10/Redist" issue
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9837/console

**Comment by sophia-guo** [comment]
```
13:13:36  build.sh : 17:13:36 : Configuring workspace inc. clone and cacerts generation ...
13:13:36  ERROR: Existing user supplied OpenJDK build root directory C:/workspace/openjdk-build/workspace/build/openjdkbuild is not empty

```

https://ci.adoptium.net/view/Test_grinder/job/Grinder/9886/console

Looks like  temurin build doesn't clean the directory if it's exist?   BUILD_CONFIG[USER_OPENJDK_BUILD_ROOT_DIRECTORY]="C:/workspace/openjdk-build/workspace/build/openjdkbuild". 

Is it safe to clean the directory on [test-azure-win2019-x64-1](https://ci.adoptium.net/computer/test-azure-win2019-x64-1) so I can move on testing? @steelhead31 ? Also https://ci.adoptium.net/computer/test-azure-win2022-x64-1/ no jq installed.

https://ci.adoptium.net/computer/test-azure-win2022-x64-3/ htis WIN_URCT_BASE="C:/Program Files (x86)/Windows Kits/10/Redist" issue

**Comment by steelhead31** [comment]
> Is it safe to clean the directory on [test-azure-win2019-x64-1](https://ci.adoptium.net/computer/test-azure-win2019-x64-1) so I can move on testing? @steelhead31 ? Also https://ci.adoptium.net/computer/test-azure-win2022-x64-1/ no jq installed.

I've cleared the directory from test-azure-win2019-x64-1 it was safe to remove  
  
test-azure-win2022-x64-2 definitely has jq installed , it maybe that jenkins hadn't picked up the change, please try again on that node.

**Comment by steelhead31** [comment]
> Also the other parser also feels not good? `temporary_speech_mark_placeholder`?
> 
> ```
> --with-ucrt-dll-dir=temporary_speech_mark_placeholderC:/PROGRA~2/WI3CF2~1/10/Redist/100226~1.0/ucrt/DLLs/x64temporary_speech_mark_placeholder
> ```

This is an existing issue in the build scripts, not much I can do about this one :)

**Comment by steelhead31** [comment]
@sophia-guo I've tidied up the win2022-build-1 workspace directory and also fixed the issue with the SDK on test-3

**Comment by sophia-guo** [comment]
@steelhead31 https://ci.adoptium.net/label/hw.arch.x86&&ci.role.test&&windows/ 

[test-azure-win2019-x64-1](https://ci.adoptium.net/computer/test-azure-win2019-x64-1) is offline
https://ci.adoptium.net/computer/test-azure-win2022-x64-1/ no jq ( not test-azure-win2022-x64-2 , both are busying right now)
 
The folder exists and job exit I mentioned this morning is the following

```
12:48:46  ERROR: Existing user supplied OpenJDK build root directory C:/workspace/openjdk-build/workspace/build/openjdkbuild is not empty
```
 https://ci.adoptium.net/view/Test_grinder/job/Grinder/9885/console

On [build-azure-win2022-x64-2](https://ci.adoptium.net/computer/build-azure-win2022-x64-2). This is a build machine, and the directory is the same for build. I'm not sure if it's safe to force delete.

**Comment by steelhead31** [comment]
> @steelhead31 https://ci.adoptium.net/label/hw.arch.x86&&ci.role.test&&windows/
> 
> [test-azure-win2019-x64-1](https://ci.adoptium.net/computer/test-azure-win2019-x64-1) is offline https://ci.adoptium.net/computer/test-azure-win2022-x64-1/ no jq ( not test-azure-win2022-x64-2 , both are busying right now)
> 
> The folder exists and job exit I mentioned this morning is the following
> 
> ```
> 12:48:46  ERROR: Existing user supplied OpenJDK build root directory C:/workspace/openjdk-build/workspace/build/openjdkbuild is not empty
> ```
> 
> https://ci.adoptium.net/view/Test_grinder/job/Grinder/9885/console
> 
> On [build-azure-win2022-x64-2](https://ci.adoptium.net/computer/build-azure-win2022-x64-2). This is a build machine, and the directory is the same for build. I'm not sure if it's safe to force delete.

test-azure-win2019-x64-1 is back online  
jq is definitely present on both test-azure-win2022-x64-1 & test-azure-win2022-x64-2

`C:/workspace/openjdk-build/workspace/build/openjdkbuild`

has been removed from build-azure-win2022-x64-2  
  
Let me know if the jq issue persists, and if there is a grinder, as I think it will need more investigation

**Comment by sophia-guo** [comment]
@steelhead31 yes, grinder still available https://ci.adoptium.net/view/Test_grinder/job/Grinder/9862/console

```
13:00:32  WARNING: JQ is not installed. Attempting To Install Via Apt-Cyg
13:00:32  Checking If Apt-Cyg Is Already Installed
13:00:32  Installing apt-cyg
13:00:34  mv: cannot move 'apt-cyg' to '/usr/local/bin/apt-cyg': Permission denied
13:00:34  -----------------------------------

```

**Comment by sophia-guo** [comment]
Seems rebuild is ok, still some directory issue

```
12:33:36  Copying found debug symbols to jdk-22.0.1+8-debug-image
12:33:40  378794 blocks
12:33:40  Finished cleaning and moving archive files from jdk-22.0.1+8
12:33:40  PERFORM_COPYING=false
12:33:40   Skipping copying of the free font library to jdk-22.0.1+8, does not apply for this version of the JDK. 
12:33:40  PERFORM_COPYING=false
12:33:40   Skipping copying of the free font library to jdk-22.0.1+8-jre, does not apply for this version of the JDK. 
12:33:41  OpenJDK JDK path will be jdk-22.0.1+8. JRE path will be jdk-22.0.1+8-jre
12:33:41  Archiving and compressing with gzip
12:33:41  Requested to archive a dir outside of workspace
12:33:41  cp: cannot stat '/cygdrive/c/comp-jdk-build/temurin-build/workspace/target/OpenJDK22U-jdk_x64_windows_hotspot_22.0.1_8.zip': No such file or directory
12:33:41  -----------------------------------
12:33:41  Rebuild_Same_JDK_Reproducibility_Test_win_0_FAILED

```
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9897/console

**Comment by sophia-guo** [comment]
I'm hitting this issue https://ci.adoptium.net/view/Test_grinder/job/Grinder/9897/ again

BUILD_CONFIG[USER_OPENJDK_BUILD_ROOT_DIRECTORY]="C:/workspace/openjdk-build/workspace/build/openjdkbuild"

```
10:29:49  build.sh : 14:29:49 : Configuring workspace inc. clone and cacerts generation ...
10:29:49  ERROR: Existing user supplied OpenJDK build root directory C:/workspace/openjdk-build/workspace/build/openjdkbuild is not empty
10:29:49  cp: cannot stat '/cygdrive/c/comp-jdk-build/temurin-build/workspace/target/OpenJDK22U-jdk_x64_windows_hotspot_22.0.1_8.zip': No such file or directory
10:29:49  -----------------------------------
10:29:49  Rebuild_Same_JDK_Reproducibility_Test_win_0_FAILED
10:29:49  -----------------------------------
```
@andrew-m-leonard what's this parameter BUILD_CONFIG[USER_OPENJDK_BUILD_ROOT_DIRECTORY] for? This is a directory ("C:/workspace/openjdk-build/workspace/build/openjdkbuild") outside of jenkins job workspace. I guess due to permission issue on windows it has to be out of jenkins job workspace. The problem is jenkins job cleanWS won't clean this directory. Is it safe for ci-jenkins-pipeline or temurin-build script to do the cleanup before build?

**Comment by steelhead31** [comment]
> Seems rebuild is ok, still some directory issue
> 
> ```
> 12:33:36  Copying found debug symbols to jdk-22.0.1+8-debug-image
> 12:33:40  378794 blocks
> 12:33:40  Finished cleaning and moving archive files from jdk-22.0.1+8
> 12:33:40  PERFORM_COPYING=false
> 12:33:40   Skipping copying of the free font library to jdk-22.0.1+8, does not apply for this version of the JDK. 
> 12:33:40  PERFORM_COPYING=false
> 12:33:40   Skipping copying of the free font library to jdk-22.0.1+8-jre, does not apply for this version of the JDK. 
> 12:33:41  OpenJDK JDK path will be jdk-22.0.1+8. JRE path will be jdk-22.0.1+8-jre
> 12:33:41  Archiving and compressing with gzip
> 12:33:41  Requested to archive a dir outside of workspace
> 12:33:41  cp: cannot stat '/cygdrive/c/comp-jdk-build/temurin-build/workspace/target/OpenJDK22U-jdk_x64_windows_hotspot_22.0.1_8.zip': No such file or directory
> 12:33:41  -----------------------------------
> 12:33:41  Rebuild_Same_JDK_Reproducibility_Test_win_0_FAILED
> ```
> 
> https://ci.adoptium.net/view/Test_grinder/job/Grinder/9897/console

I've manually removed this completely now, from test-2 :)

**Comment by sophia-guo** [comment]
Seems if BUILD_CONFIG[USER_OPENJDK_BUILD_ROOT_DIRECTORY]="C:/workspace/openjdk-build/workspace/build/openjdkbuild" the archived jdk zip file be 
`/cygdrive/c/workspace/openjdk-build/workspace/target/`

Does that mean the archived zip file will always be $USER_OPENJDK_BUILD_ROOT_DIRECTORY/../../target, I will give it a try.

**Comment by andrew-m-leonard** [comment]
> Seems if BUILD_CONFIG[USER_OPENJDK_BUILD_ROOT_DIRECTORY]="C:/workspace/openjdk-build/workspace/build/openjdkbuild" the archived jdk zip file be `/cygdrive/c/workspace/openjdk-build/workspace/target/`
> 
> Does that mean the archived zip file will always be $USER_OPENJDK_BUILD_ROOT_DIRECTORY/../../target, I will give it a try.
> 
> Looks good https://ci.adoptium.net/view/Test_grinder/job/Grinder/9917/

@sophia-guo @steelhead31  this is not quite right, the openjdk build directory location is un-related to location of the "target" folder, especially when USER_OPENJDK_BUILD_ROOT_DIRECTORY is used.

Hopefully the following will explain.
1. First an fyi, note the Windows "cludge!" which moves the context WORKSPACE to C:/workspace/openjdk-build: https://github.com/adoptium/ci-jenkins-pipelines/blob/e6947980814dc85266954880202c6adfedadbcfa/pipelines/build/common/openjdk_build_pipeline.groovy#L2085
3.

**Comment by sophia-guo** [comment]
Grinder https://ci.adoptium.net/view/Test_grinder/job/Grinder/10003/

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Review by steelhead31 — APPROVED** [review]
LGTM!

**Comment by sophia-guo** [comment]
> https://github.com/adoptium/temurin-build/pull/3778#issuecomment-2104351827

@andrew-m-leonard Thanks! Very clear and helpful!

**Pull request merged**
