### PR TITLE
actions: fix failing macOS builds

### PR DESCRIPTION
**Pull request by gdams**
Fixes the currently failing macOS build jobs

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@gdams - Maybe we should set that to 12 now that 13 is out?

**Comment by gdams** [comment]
> @gdams - Maybe we should set that to 12 now that 13 is out?

@karianna 11 is the latest supported build that we can build OpenJDK on so I'll leave it as that.

**Review by tellison — APPROVED** [review]

**Comment by tellison** [comment]
+1 to having a specific version anyway

**Pull request merged**
