### PR TITLE
doc: Update RELEASING.md based on Jan2022 experiences

### PR DESCRIPTION
**Pull request by sxa**
Fixes https://github.com/adoptium/temurin-build/issues/2848

[Link to new version in my branch](https://github.com/sxa/openjdk-build/blob/release_updates_feb22/RELEASING.md)

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Some of the linter comments make sense this time around

**Comment by sxa** [comment]
> Some of the linter comments make sense this time around

I think the only applicatble one is "website" -> "site".

I'm not personally convinced that "add a banner to the site" is as clear, but willing to hear alternative opinions ...

**Comment by karianna** [comment]
I think website is better as well - over zealous linter :-).  Not sure how to configure it?

**Comment by sxa** [comment]
> I think website is better as well - over zealous linter :-). Not sure how to configure it?

Ditto ;-)

**Pull request merged**
