### PR TITLE
Update build triage script to include pipeline analysis

### PR DESCRIPTION
**Pull request by adamfarley**
This update primarily allows the script to correctly identify
tag-driven build pipelines. JDK8 has three types of these, and
all types should be located where possible.

We can also ignore pipelines that are still running, as these will
have incomplete results.

User-launched pipelines will also be ignored, as the script cannot
yet spot the difference between a rerun using default options,
and an experimental rerun whose outcome should not be used to
indicate the overall health of the build system.

I have also repaired the bug where unstable builds are erroneously
included in the list of failed builds. Unstable builds are typically
passed builds which have a number of failed post-build unit tests.

Lastly, we no longer expect arm32 builds on JDK21 and up.

Minor cosmetic improvements included.

### CODE REVIEW

**Comment by adamfarley** [comment]
Tested here: https://github.com/adamfarley/temurin-build/actions/runs/8190313614/job/22397008637
Output issue here: https://github.com/adamfarley/temurin-build/issues/65

Linter in progress.

**Comment by adamfarley** [comment]
Made several style changes to satisfy the linter, and also improved logging.

Also excluded the "build" github action for future build triage script changes. 

We don't need to test the build process against changes to the triage script, because build triage happens after the build pipeline is complete.

**Comment by adamfarley** [comment]
Added a couple of updates to the autotriage workflow:

- This workflow can now be run manually from the website if needed (for testing improvements).
image
- Amended the first few lines to make the action name display correctly on the web interface.

The latest code changes were tested here: https://github.com/adamfarley/temurin-build/actions/runs/8203403503
With the output issue located here: https://github.com/adamfarley/temurin-build/issues/66

**Comment by adamfarley** [comment]
Ready for reviews. Adding a link to #temurin-build Slack.

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Review by steelhead31 — APPROVED** [review]
LGTM

**Pull request merged**
