### PR TITLE
Integrate CycloneDX SBOM API into build.sh

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Integrate the new CycloneDX Java API plugin into the build-scripts bill of materials generation.

This PR creates the SBOM file: ${BUILD_CONFIG[WORKSPACE_DIR]}/${BUILD_CONFIG[TARGET_DIR]}/metadata/sbom.json

A 2nd PR for ci-jenkins-pipelines will create a new Artifact from sbom.json.

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Jenkins built SBOM:
```
16:16:52  CycloneDX SBOM:
16:16:52  {
16:16:52    "bomFormat" : "CycloneDX",
16:16:52    "specVersion" : "1.3",
16:16:52    "version" : 1,
16:16:52    "metadata" : {
16:16:52      "timestamp" : "2022-03-08T16:16:46Z",
16:16:52      "component" : {
16:16:52        "name" : "Temurin",
16:16:52        "type" : "application"
16:16:52      },
16:16:52      "manufacture" : {
16:16:52        "name" : "Eclipse Foundation",
16:16:52        "url" : [
16:16:52          "https://www.eclipse.org/"
16:16:52        ]
16:16:52      },
16:16:52      "properties" : [
16:16:52        {
16:16:52          "name" : "OS_KERNEL",
16:16:52          "value" : "Linux"
16:16:52        },
16:16:52        {
16:16:52          "name" : "OS_ARCHITECTURE",
16:16:52          "value" : "X86_64"
16:16:52        },
16:16:52        {
16:16:52          "name" : "VARIANT",
16:16:52          "value" : "Temurin"
16:16:52        }
16:16:52      ]
16:16:52    },
16:16:52    "components" : [
16:16:52      {
16:16:52        "author" : "Vendor: Adoptium",
16:16:52        "group" : "Eclipse Temurin",
16:16:52        "name" : "Temurin",
16:16:52        "version" : "19+9",
16:16:52        "type" : "application"
16:16:52      },
16:16:52      {
16:16:52        "name" : "JDK",
16:16:52        "description" : "Temurin JDK Component",
16:16:52        "properties" : [
16:16:52          {
16:16:52            "name" : "scmRef",
16:16:52            "value" : "jdk-19+1_adopt-2871-g4092ff6cb37"
16:16:52          },
16:16:52          {
16:16:52            "name" : "buildRef",
16:16:52            "value" : "https://github.com/andrew-m-leonard/openjdk-build/commit/2ac0106"
16:16:52          },
16:16:52          {
16:16:52            "name" : "full_version_output",
16:16:52            "value" : "openjdk version \"19\" 2022-09-20 OpenJDK Runtime Environment Temurin-19+9 (build 19+9) OpenJDK 64-Bit Server VM Temurin-19+9 (build 19+9, mixed mode, sharing)"
16:16:52          },
16:16:52          {
16:16:52            "name" : "makejdk_any_platform_args",
16:16:52            "value" : "--clean-git-repo --jdk-boot-dir /home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-x64-temurin/jdk-19 --configure-args --disable-warnings-as-errors --with-source-date=updated --with-build-user=adoptium --enable-ccache --disable-ccache --with-source-date=version --with-version-build=9 --with-vendor-version-string=Temurin-19+9 --without-version-pre --without-version-opt --target-file-name OpenJDK-jdk_x64_linux_hotspot_2022-03-08-16-09.tar.gz --create-sbom -b repro -r https://github.com/andrew-m-leonard/jdk-1 --skip-freetype --use-jep319-certs --create-debug-image --build-variant temurin jdk"
16:16:52          },
16:16:52          {
16:16:52            "name" : "make_command_args",
16:16:52            "value" : "make product-images test-image static-libs-image"
16:16:52          }
16:16:52        ]
16:16:52      },
16:16:52      {
16:16:52        "name" : "ALSA",
16:16:52        "description" : "dependency_version_alsa",
16:16:52        "properties" : [
16:16:52          {
16:16:52            "name" : "url",
16:16:52            "value" : "https://ftp.osuosl.org/pub/blfs/conglomeration/alsa-lib/alsa-lib-1.1.6.tar.bz2"
16:16:52          }
16:16:52        ]
16:16:52      }
16:16:52    ]
16:16:52  }
```

**Review by smlambert — APPROVED** [review]
LGTM, thanks @andrew-m-leonard - FYI, I am in favour of bringing this in prior to the release next week.

**Review by sxa — APPROVED** [review]
LGTM, although I'm wondering if we should look at splitting out the SBOM functions into a separate script under `common` that's sourced to keep it all in one tidy place at some point in the future?

**Comment by andrew-m-leonard** [comment]
> LGTM, although I'm wondering if we should look at splitting out the SBOM functions into a separate script under `common` that's sourced to keep it all in one tidy place at some point in the future?

This will be the plan yes, as it's going to get a lot more complex I suspect with more detailed info.

**Pull request merged**
