### PR TITLE
Using jimage, jmod of compared jdks

### PR DESCRIPTION
**Pull request by sophia-guo**
Update mkdir with -p
Update some unzip command to turn off the verbose output

relate https://github.com/adoptium/temurin-build/issues/3245

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Another issue is running  `      "${JDK_DIR}/bin/jmod" extract --dir "${expand_dir}" "$f"` on jenkins with linux 64  get error message

```
Unzipping /home/jenkins/workspace/Sophia_pipeline/original/jmods/jdk.nio.mapmode.jmod
Error occurred during initialization of VM
Failed setting boot class path.
```
Running locally on mac no issue with `jmod extract`. @andrew-m-leonard any idea?

**Comment by andrew-m-leonard** [comment]
> Another issue is running ` "${JDK_DIR}/bin/jmod" extract --dir "${expand_dir}" "$f"` on jenkins with linux 64 get error message
> 
> ```
> Unzipping /home/jenkins/workspace/Sophia_pipeline/original/jmods/jdk.nio.mapmode.jmod
> Error occurred during initialization of VM
> Failed setting boot class path.
> ```
> 
> Running locally on mac no issue with `jmod extract`. @andrew-m-leonard any idea?

@sophia-guo is it trying to expand itself? ie. is "$f" within "${JDK_DIR}/bin/jmod" ? The "jmod" been used needs to be outside the original being "un-packed", as when it is unpacked it becomes an un-usable JDK to execute..

**Comment by sophia-guo** [comment]
No, the file is not in bin/jmod. 
Command is something like:
`/home/jenkins/workspace/Sophia_pipeline/original/bin/jmod extract --dir /home/jenkins/workspace/Sophia_pipeline/original/jmods/expanded_jdk.management.jmod /home/jenkins/workspace/Sophia_pipeline/original/jmods/jdk.management.jmod`

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Pull request merged**
