### PR TITLE
Ensure LD_LIBRARY_PATH set when building using a linux devkit

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
When building using a linux devkit, the LD_LIBRARY_PATH needs setting prior to the build to use the devkit sysroot lib64:lib

### CODE REVIEW

**Review by sxa — APPROVED** [review]
I never liked the `REMATCH` syntax, but if it works I'm ok with it :-)
Do these need to be in `prepareWorkspace.sh` as well as `linux.sh`?
I'll approve regardless for this cycle but it would be good to avoid the dupliation in the future if possible.

**Comment by andrew-m-leonard** [comment]
> I never liked the `REMATCH` syntax, but if it works I'm ok with it :-) Do these need to be in `prepareWorkspace.sh` as well as `linux.sh`? I'll approve regardless for this cycle but it would be good to avoid the dupliation in the future if possible.

I could do that better yes

**Comment by andrew-m-leonard** [comment]
> I never liked the `REMATCH` syntax, but if it works I'm ok with it :-) Do these need to be in `prepareWorkspace.sh` as well as `linux.sh`? I'll approve regardless for this cycle but it would be good to avoid the dupliation in the future if possible.

yep, i've resolved it into one place

**Review by smlambert — APPROVED** [review]
LGTM

**Pull request merged**
