### PR TITLE
Add JDK JRE version test for openj9 jdk8

### PR DESCRIPTION
**Pull request by LongyuZhang**
- This test will test the jre jave version under jdk folder
- Only add for openj9 jdk8
Related Issue: ibm_git/infrastructure/issues/7925

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test LInks (Adoptium Grinder):
- windows: [7318](https://ci.adoptium.net/job/Grinder/7318/)
- Alinux: [7319](https://ci.adoptium.net/job/Grinder/7319/)

**Comment by LongyuZhang** [comment]
FYI @smlambert @sophia-guo @llxia

**Review by llxia — APPROVED** [review]
Thanks @LongyuZhang

**Review by karianna — APPROVED** [review]

**Review by smlambert — APPROVED** [review]

**Comment by karianna** [comment]
Hmmm, I thought code freeze bot would block this

**Pull request merged**
