### PR TITLE
Use bundled zlib instead of system for JDK21+

### PR DESCRIPTION
**Pull request by sxa**
Ref https://github.com/adoptium/temurin-build/issues/3013#issuecomment-1600900780

### CODE REVIEW

**Comment by karianna** [comment]
jdk8u on Mac fails as well, but seems unrelated

**Comment by sxa** [comment]
Linux failure will be fixed by #3401 - unrelated to this PR

**Comment by sxa** [comment]
> jdk8u on Mac fails as well, but seems unrelated

[The mac one](https://github.com/adoptium/temurin-build/actions/runs/5336924946/jobs/9690483286) is particularly odd:
```
clang: error: no such file or directory: '/dev/fd/8'
clang: error: no input files
dtrace: failed to compile script /Users/runner/work/temurin-build/temurin-build/workspace/build/src/hotspot/src/os/bsd/dtrace/hotspot_jni.d: Preprocessor failed to process input program
```
Re-running at https://github.com/adoptium/temurin-build/actions/runs/5344957027/jobs/9689991298?pr=3401 and it looks to have passed that point.

**Review by gdams — APPROVED** [review]

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Pull request merged**
