### PR TITLE
docker: add windows build support

### PR DESCRIPTION
**Pull request by gdams**
This PR allows us to start using dynamic windows x64 machines with docker images to produce builds. Currently, I only have a Visual Studio 2017 image so I've started with **JDK11+**. This change also only applies to **Hotspot** builds right now as I'll need to add further dependencies to the docker image to support the builds.

One area of improvement is the queue times. A dynamic machine takes ~5 minutes to be deployed which is fine but the docker pull takes ~10 minutes. I'm working on ways to improve this by using Azure container registry and storing a copy in the same datacentre as the machines.

## TEST BUILDS:

JDK11 - https://ci.adoptopenjdk.net/view/build-tester/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/323/console

JDK15 - https://ci.adoptopenjdk.net/view/build-tester/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk15u/job/jdk15u-windows-x64-hotspot/238/console

JDK16 - https://ci.adoptopenjdk.net/view/build-tester/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/271/console

### CODE REVIEW

**Comment by gdams** [comment]
run tests

**Comment by karianna** [comment]
@gdams - Did you want to continue with this PR or are you happy to park it given our [refactoring efforts](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1612353108094700)?

**Comment by M-Davies** [comment]
@gdams Ref the final point of https://github.com/AdoptOpenJDK/openjdk-build/issues/2455, can we close this and reopen over at `ci-jenkins-pipelines`?

**Comment by karianna** [comment]
@gdams rebase required on this one

**Pull request closed without merging**
