### PR TITLE
Build OpenJ9 Windows jdk19+ with VS2022, and disable ccache

### PR DESCRIPTION
**Pull request by pshipton**
OpenJ9 was missing the change to disable ccache for all versions.

Issue https://github.com/eclipse-openj9/openj9/issues/16701

### CODE REVIEW

**Comment by pshipton** [comment]
@AdamBrousseau fyi

**Review by AdamBrousseau — APPROVED** [review]

**Review by karianna — CHANGES_REQUESTED** [review]
In /github/workspace/build-farm/platform-specific-configurations/windows.sh line 227:
fi
^-- SC1089 (error): Parsing stopped here. Is this keyword correctly matched up?

**Comment by pshipton** [comment]
Oops, fixed now.

**Comment by karianna** [comment]
OK the Alpine build is failing because it is merging/generating a file that has a merge conflict: <<<<<<< HEAD

No idea where this is coming from as a GitHub code search indicates that's nowhere in the entire Adoptium org.

**Review by sxa — COMMENTED** [review]
Does `--disable-ccache` do anything on Windows JDK builds? I didn't think it was possible to use it there.

**Comment by pshipton** [comment]
> Does --disable-ccache do anything on Windows JDK builds? I didn't think it was possible to use it there.

I don't know, I'm just making it consistent. 32-bit builds use it, non-openj9 builds use it, and openj9 jdk8 64-bit uses it. My change uses it for openj9 64-bit builds of all versions.

**Comment by sxa** [comment]
@karianna Are you happy with this now after Peter addressed your request?

**Comment by karianna** [comment]
> OK the Alpine build is failing because it is merging/generating a file that has a merge conflict: <<<<<<< HEAD
> 
> No idea where this is coming from as a GitHub code search indicates that's nowhere in the entire Adoptium org.

The Alpine build still seems to have a merge conflict?

**Comment by gdams** [comment]
I think we should try and align hotspot/openj9 better here. @sxa I think we were talking about bumping the Temurin builds to VS 2022 as well?

**Comment by sxa** [comment]
> > OK the Alpine build is failing because it is merging/generating a file that has a merge conflict: <<<<<<< HEAD
> > No idea where this is coming from as a GitHub code search indicates that's nowhere in the entire Adoptium org.
> 
> The Alpine build still seems to have a merge conflict?

That's the separate branch that MSFT is maintaining I believe - @gdams can you check this one?

**Comment by sxa** [comment]
> I think we should try and align hotspot/openj9 better here. @sxa I think we were talking about bumping the Temurin builds to VS 2022 as well?

Possibly but we can do that under a separate PR if desired. At the moment all the work that is being done to enable reproducibility for Temurin is on VS2019 and additional work would be required to move it up.

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Comment by AdamBrousseau** [comment]
Can this be merged?

**Comment by karianna** [comment]
I think we're still in release freeze.

**Review by sxa — APPROVED** [review]

**Pull request merged**
