### PR TITLE
restoring the --openjdk-source-location after PR#2702

### PR DESCRIPTION
**Pull request by judovana**
https://github.com/adoptium/temurin-build/issues/4065

I may have limited availability today. If it is ok, feel free to merge as necessary.

### CODE REVIEW

**Comment by judovana** [comment]
All linux builds failef. Seem s unrelated. Seems related to removal of node16

**Comment by judovana** [comment]
@sxa  @ anybody... may I ask for review if possible?

**Comment by sxa** [comment]
> @sxa @ anybody... may I ask for review if possible?

I'm having a long overdue PR review catch up and have just made it to the temurin-build repo so I'm on it now ;-)

> All linux builds failed. Seems unrelated. Seems related to removal of node16

Covered in https://github.com/adoptium/temurin-build/pull/4064 so if you rebase that should fix itself.

**Review by sxa — APPROVED** [review]
LGTM :-)

Adding Scott as another reviewer sine he knows his way around a shell script too.

**Review by steelhead31 — APPROVED** [review]
Looks good.

**Comment by judovana** [comment]
Thanx! I had rebased to see the actions.

**Pull request merged**
